/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.RecordKeeping;

import java.sql.*;

import javax.swing.*;
import java.awt.*;


/**
 *
 * @author ryan3
 */
public class adminTeacherFrame extends javax.swing.JFrame {

    String url = "jdbc:mysql://127.0.0.1:3306/";
    //database name
    String dbName = "GTIRecords";

    //username for connecting to local host
    String userName = "root";
    //password for connecting to local host
    String password = "452012";

    public String courseCode = "";
    public Integer assignmntID = 0;
    /**
     * Creates new form teacherFrame
     */
    public adminTeacherFrame() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonAdd = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jTextFieldSearch = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldTeacherID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldFName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldSurname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldPPSN = new javax.swing.JTextField();
        jTextFieldDOB = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldAL1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldAL2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldEircode = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldPN = new javax.swing.JTextField();
        jButtonClear = new javax.swing.JButton();
        jComboBoxCounty = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxModule = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jComboBoxCourse = new javax.swing.JComboBox<>();
        jButtonStudent = new javax.swing.JButton();
        jButtonReports = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Teacher");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(0, 204, 102));
        jPanel2.setForeground(new java.awt.Color(204, 0, 0));

        jButtonAdd.setBackground(new java.awt.Color(153, 153, 153));
        jButtonAdd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonAdd.setText("Add");
        jButtonAdd.setToolTipText("Add Student ");
        jButtonAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonAddMouseExited(evt);
            }
        });
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonDelete.setBackground(new java.awt.Color(153, 153, 153));
        jButtonDelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonDelete.setText("Delete");
        jButtonDelete.setToolTipText("Delete Student");
        jButtonDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonDeleteMouseExited(evt);
            }
        });
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonUpdate.setBackground(new java.awt.Color(153, 153, 153));
        jButtonUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonUpdate.setText("Update");
        jButtonUpdate.setToolTipText("Update Student");
        jButtonUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonUpdateMouseExited(evt);
            }
        });
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonLogout.setBackground(new java.awt.Color(153, 153, 153));
        jButtonLogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonLogout.setText("Logout");
        jButtonLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonLogoutMouseExited(evt);
            }
        });
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTextFieldSearch.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jTextFieldSearch.setToolTipText("Search via Teacher ID");
        jTextFieldSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSearchKeyTyped(evt);
            }
        });

        jButtonSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Teacher ID:");

        jTextFieldTeacherID.setEditable(false);
        jTextFieldTeacherID.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldTeacherID.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jTextFieldTeacherID.setEnabled(false);
        jTextFieldTeacherID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTeacherIDKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("First Name:");

        jTextFieldFName.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jTextFieldFName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldFNameKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Surname:");

        jTextFieldSurname.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jTextFieldSurname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSurnameKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Email:");

        jTextFieldEmail.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jTextFieldEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEmailKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("PPSN:");

        jTextFieldPPSN.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jTextFieldPPSN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPPSNKeyTyped(evt);
            }
        });

        jTextFieldDOB.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jTextFieldDOB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldDOBFocusGained(evt);
            }
        });
        jTextFieldDOB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDOBKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("DOB:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Address Line 1:");

        jTextFieldAL1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jTextFieldAL1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldAL1KeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Adress Line 2:");

        jTextFieldAL2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jTextFieldAL2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldAL2KeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("County:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Eircode:");

        jTextFieldEircode.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jTextFieldEircode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEircodeKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Phone Number:");

        jTextFieldPN.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jTextFieldPN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPNKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPNKeyTyped(evt);
            }
        });

        jButtonClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jComboBoxCounty.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jComboBoxCounty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Antrim", "Armagh", "Carlow", "Cavan", "Clare", "Cork", "Derry", "Donegal", "Down", "Dublin", "Fermanagh", "Galway", "Kerry", "Kildare", "Kilkenny", "Laois", "Leitrim", "Limerick", "Longford", "Louth", "Mayo", "Meath", "Monaghan", "Offaly", "Roscommon", "Sligo", "Tipperary", "Tyrone", "Waterford", "Westmeath", "Wexford", "Wicklow" }));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Module:");

        jComboBoxModule.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jComboBoxModule.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Project Management", "OOP", "Software Architecture", "GUI Programming", "Leadership", "Work Experience", "Mathematics", "Relational Database", "Mobile Technologies" }));
        jComboBoxModule.setEnabled(false);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Course:");

        jComboBoxCourse.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jComboBoxCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Advanced Software Development", "Dog Grooming", "Emergency Care Services", "Programming and Software Development", "Advanced Animal Science" }));
        jComboBoxCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCourseActionPerformed(evt);
            }
        });

        jButtonStudent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonStudent.setText("Add Student");
        jButtonStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStudentActionPerformed(evt);
            }
        });

        jButtonReports.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonReports.setText("Reports");
        jButtonReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReportsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldTeacherID, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldFName, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldPPSN, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldAL1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldAL2, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxCounty, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldEircode, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButtonStudent)
                                .addGap(47, 47, 47)
                                .addComponent(jButtonReports)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonClear))
                            .addComponent(jTextFieldPN)
                            .addComponent(jComboBoxModule, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxCourse, 0, 379, Short.MAX_VALUE))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldTeacherID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldPPSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldAL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldAL2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBoxCounty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldEircode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jComboBoxCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jComboBoxModule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButtonClear)
                    .addComponent(jButtonStudent)
                    .addComponent(jButtonReports))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSearch)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearch))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTeacherIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTeacherIDKeyTyped
        // Validation -  only digits allowed
        char keyTyped = evt.getKeyChar();
       
        if (!(Character.isDigit(keyTyped))) {

            evt.consume();

        }
    }//GEN-LAST:event_jTextFieldTeacherIDKeyTyped

    private void jTextFieldFNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFNameKeyTyped
        // Validation -  only letters allowed
        char keyTyped = evt.getKeyChar();

        if (!(Character.isLetter(keyTyped))) {

            evt.consume();

        }
    }//GEN-LAST:event_jTextFieldFNameKeyTyped

    private void jTextFieldSurnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSurnameKeyTyped
        // Validation -  only letters allowed
        char keyTyped = evt.getKeyChar();

        if (!(Character.isLetter(keyTyped))) {

            evt.consume();

        }
    }//GEN-LAST:event_jTextFieldSurnameKeyTyped

    private void jTextFieldEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEmailKeyTyped
        // Validation -  spaces not allowed
        char keyTyped = evt.getKeyChar();

        if (Character.isSpace(keyTyped)) {

            evt.consume();

        }
    }//GEN-LAST:event_jTextFieldEmailKeyTyped

    private void jTextFieldPPSNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPPSNKeyTyped
        // Validation -  only letters and digits allowed
        char keyTyped = evt.getKeyChar();
        String PPSN = jTextFieldPPSN.getText();

        if (!(Character.isLetterOrDigit(keyTyped))) {

            evt.consume();

        }
        //if ppsn is bigger than 8 charachters long consume charachter
        if (PPSN.length() > 7) {
            evt.consume();
        }

    }//GEN-LAST:event_jTextFieldPPSNKeyTyped

    private void jTextFieldDOBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDOBKeyTyped
//         Validation -  only digits allowed
        char keyTyped = evt.getKeyChar();
        String DOB = jTextFieldDOB.getText();

        if (!(Character.isDigit(keyTyped) || isSlash(keyTyped))) {

            evt.consume();

        }
//if dob is bigger than 10 charachters long consume charachter
        if (DOB.length() > 9) {
            evt.consume();
        }

    }//GEN-LAST:event_jTextFieldDOBKeyTyped

    private void jTextFieldAL1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAL1KeyTyped
        // Validation -  only letters, digits and spaces allowed
        char keyTyped = evt.getKeyChar();

        if (!(Character.isLetterOrDigit(keyTyped) || Character.isSpace(keyTyped))) {

            evt.consume();

        }
    }//GEN-LAST:event_jTextFieldAL1KeyTyped

    private void jTextFieldAL2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAL2KeyTyped
        // Validation -  only letters, digits and spaces allowed
        char keyTyped = evt.getKeyChar();

        if (!(Character.isLetterOrDigit(keyTyped) || Character.isSpace(keyTyped))) {

            evt.consume();

        }
    }//GEN-LAST:event_jTextFieldAL2KeyTyped

    private void jTextFieldEircodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEircodeKeyTyped
        // Validation -  only letters, digits and spaces allowed
        char keyTyped = evt.getKeyChar();
        String eircode = jTextFieldEircode.getText();
        if (!(Character.isLetterOrDigit(keyTyped))) {

            evt.consume();

        }

        if (eircode.length() > 6) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldEircodeKeyTyped

    private void jTextFieldPNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPNKeyTyped
        // Validation -  only digits allowed
        char keyTyped = evt.getKeyChar();
        String PN = jTextFieldPN.getText();

        if (!(Character.isDigit(keyTyped))) {

            evt.consume();

        }

        // if phone number is bigger than 10 digits consume charachter
        if (PN.length() > 9) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldPNKeyTyped

    private void jTextFieldPNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPNKeyReleased
        String PN = jTextFieldPN.getText();
        // if phone number doesent start with 0 consume char
        if (!(PN.startsWith("0"))) {
            evt.consume();
            jTextFieldPN.setText("");
        }
    }//GEN-LAST:event_jTextFieldPNKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // declareing variables for validation purposes below 
        String DOB = jTextFieldDOB.getText();
        String eircode = jTextFieldEircode.getText();
        String fName = jTextFieldFName.getText();
        String sName = jTextFieldSurname.getText();
        String PPSN = jTextFieldPPSN.getText();
        String address = jTextFieldAL1.getText();
        String address2 = jTextFieldAL2.getText();
        String email = jTextFieldEmail.getText();
        String phoneNumber = jTextFieldPN.getText();
        //if first name is not entered give error message
        if (fName.length() == 0) {
            JOptionPane.showMessageDialog(null, "Please Enter your First Name!");
            jTextFieldFName.setText("");

            //if surname is not entered give error message  
        } else if (sName.length() == 0) {
            JOptionPane.showMessageDialog(null, "Please Enter your Surname!");
            jTextFieldSurname.setText("");

            //if email is not enetered correctly give error message
        } else if (!(email.contains("@") && email.contains("."))) {
            JOptionPane.showMessageDialog(null, "Invalid format email needs @ and .");
            jTextFieldEmail.setText("");
            // if ppsn is less than 8 charachters give error message
        } else if (PPSN.length() < 8) {
            JOptionPane.showMessageDialog(null, "PPSN must be 8 charachters");
            jTextFieldPPSN.setText("");

            //if dob is not enetered give error message
        } else if (DOB.length() < 10) {
            JOptionPane.showMessageDialog(null, "Please Enter your Date of Birth!");
            jTextFieldDOB.setText("");
            // if address is too short give error message
        } else if (address.length() < 5) {
            JOptionPane.showMessageDialog(null, "Please Enter your full Address!");
            jTextFieldAL1.setText("");

            // if address is too short give error message
        } else if (address2.length() < 5) {
            JOptionPane.showMessageDialog(null, "Please Enter your full Address!");
            jTextFieldAL2.setText("");

            //  if eircode is not enetered give error message
        } else if (eircode.length() < 7) {
            JOptionPane.showMessageDialog(null, "Please Enter valid Eircode!");
            jTextFieldEircode.setText("");

            //  if phone number is not enetered give error message
        } else if (phoneNumber.length() < 10) {
            JOptionPane.showMessageDialog(null, "Phone number must be 10 digits");
            jTextFieldPN.setText("");

           
        } else {
            // create teacher object and set teacher varaibles
            Teacher t = new Teacher(0, jTextFieldFName.getText(), jTextFieldSurname.getText(), jTextFieldEmail.getText(), jTextFieldPPSN.getText(), jTextFieldDOB.getText(), jTextFieldAL1.getText(), jTextFieldAL2.getText(), jComboBoxCounty.getSelectedItem().toString(), jTextFieldEircode.getText(), Integer.parseInt(jTextFieldPN.getText()), jComboBoxModule.getSelectedItem().toString());
            
            // declare variables for recording module deatils
            String course = jComboBoxCourse.getSelectedItem().toString();
            String moduleName = t.getModule();
            String moduleCode = "";
            String courseCode = "";
            String credits = "";
            // if module is project management set module code, course code and credits
            if (moduleName.equals("Project Management")){
                moduleCode = "6N4090";
                courseCode = "6M0691";
                credits = "QQI Level 6 Award";
            } else if (moduleName.equals("Object Oriented Programming")){
                moduleCode = "6N2108";
                courseCode = "6M0691";
                credits = "QQI Level 6 Award";
            } else if (moduleName.equals("Software Architecture") && course.equals("Advanced Software Development")){
                moduleCode = "6N1449";
                courseCode = "6M0691";
                credits = "QQI Level 6 Award";
            } else if (moduleName.equals("Graphical User Interface Programming")){
                moduleCode = "6N0736";
                courseCode = "6M0691";
                credits = "QQI Level 6 Award";
            } else if (moduleName.equals("Leadership")){
                moduleCode = "6N2191";
                courseCode = "6M0691";
                credits = "QQI Level 6 Award";
            } else if (moduleName.equals("Work Experience") && course.equals("Advanced Software Development")){
                moduleCode = "6N1946";
                courseCode = "6M0691";
                credits = "QQI Level 6 Award";
            } else if (moduleName.equals("Mathematics")){
                moduleCode = "6N3395";
                courseCode = "6M0691";
                credits = "QQI Level 6 Award";
            } else if (moduleName.equals("Relational Database")){
                moduleCode = "6N4785";
                courseCode = "6M0691";
                credits = "QQI Level 6 Award";
            } else if (moduleName.equals("Mobile Technologies") && course.equals("Advanced Software Development")){
                moduleCode = "6N0734";
                courseCode = "6M0691";
                credits = "QQI Level 6 Award";
            }
            
            if (moduleName.equals("Animal Anatomy and Physiology")){
                moduleCode = "5N0750";
                courseCode = "5M2768";
                credits = "QQI Level 5 Award";
            } else if (moduleName.equals("Animal Welfare")){
                moduleCode = "5N0753";
                courseCode = "5M2768";
                credits = "QQI Level 5 Award";
            } else if (moduleName.equals("Animal Grooming") && course.equals("Dog Grooming")){
                moduleCode = "5N0752";
                courseCode = "5M2768";
                credits = "QQI Level 5 Award";
            } else if (moduleName.equals("Veterinary Assisting Skills")){
                moduleCode = "5N1363";
                courseCode = "5M2768";
                credits = "QQI Level 5 Award";
            } else if (moduleName.equals("Communications") && course.equals("Dog Grooming")){
                moduleCode = "5N0690";
                courseCode = "5M2768";
                credits = "QQI Level 5 Award";
            } else if (moduleName.equals("Work Experience") && course.equals("Dog Grooming")){
                moduleCode = "5N1356";
                courseCode = "5M2768";
                credits = "QQI Level 5 Award";
            } else if (moduleName.equals("Word Processing") && course.equals("Dog Grooming")){
                moduleCode = "5N1358";
                courseCode = "5M2768";
                credits = "QQI Level 5 Award";
            } else if (moduleName.equals("Safety & Health at Work") && course.equals("Dog Grooming")){
                moduleCode = "5N1794";
                courseCode = "5M2768";
                credits = "QQI Level 5 Award";
            } 
            
            if (moduleName.equals("Emergency Department Care Skills")){
                moduleCode = "5N4890";
                courseCode = "5M4468";
                credits = "QQI Level 6 Award";
            } else if (moduleName.equals("Care Provision & Practice")){
                moduleCode = "5N2705";
                courseCode = "5M4468";
                credits = "QQI Level 5 Award";
            } else if (moduleName.equals("Infection Prevention and Control") ){
                moduleCode = "5N3734";
                courseCode = "5M4468";
                credits = "QQI Level 5 Award";
            } else if (moduleName.equals("Care of the Older Person")){
                moduleCode = "5N2706";
                courseCode = "5M4468";
                credits = "QQI Level 5 Award";
            } else if (moduleName.equals("Anatomy & Physiology")){
                moduleCode = "5N0749";
                courseCode = "5M4468";
                credits = "QQI Level 5 Award";
            } else if (moduleName.equals("Safety and Health at Work") && course.equals("Emergency Care Services") ){
                moduleCode = "5N1794";
                courseCode = "5M4468";
                credits = "QQI Level 5 Award";
            } else if (moduleName.equals("Word Processing") && course.equals("Emergency Care Services")){
                moduleCode = "5N1358";
                courseCode = "5M4468";
                credits = "QQI Level 5 Award";
            } else if (moduleName.equals("Work Experience") && course.equals("Emergency Care Services")){
                moduleCode = "5N1356";
                courseCode = "5M4468";
                credits = "QQI Level 5 Award";
            } else if (moduleName.equals("Communications") && course.equals("Emergency Care Services")){
                moduleCode = "5N0690";
                courseCode = "5M4468";
                credits = "QQI Level 5 Award";
            }
            
            if (moduleName.equals("Programming & Design Principles")){
                moduleCode = "5N2927";
                courseCode = "5M0529";
                credits = "QQI Level 5 Award";
            } else if (moduleName.equals("Fundamentals of OOP")){
                moduleCode = "5N0541";
                courseCode = "5M0529";
                credits = "QQI Level 5 Award";
            } else if (moduleName.equals("Software Architecture") && course.equals("Programming and Software Development")){
                moduleCode = "5N2772";
                courseCode = "5M0529";
                credits = "QQI Level 5 Award";
            } else if (moduleName.equals("Maths for Information Technology")){
                moduleCode = "5N18396";
                courseCode = "5M0529";
                credits = "QQI Level 5 Award";
            } else if (moduleName.equals("Team working")){
                moduleCode = "5N1367";
                courseCode = "5M0529";
                credits = "QQI Level 5 Award";
            } else if (moduleName.equals("Work Experience") && course.equals("Programming and Software Development")){
                moduleCode = "5N1356";
                courseCode = "5M0529";
                credits = "QQI Level 5 Award";
            } else if (moduleName.equals("Database Methods")){
                moduleCode = "5N0783";
                courseCode = "5M0529";
                credits = "QQI Level 5 Award";
            } else if (moduleName.equals("Communications") && course.equals("Programming and Software Development")){
                moduleCode = "5N0690";
                courseCode = "5M0529";
                credits = "QQI Level 5 Award";
            } else if (moduleName.equals("Mobile Technologies") && course.equals("Programming and Software Development")){
                moduleCode = "5N0580";
                courseCode = "5M0529";
                credits = "QQI Level 5 Award";
            }
            
            if (moduleName.equals("Animal Science and Health")){
                moduleCode = "6N5565";
                courseCode = "6M5153";
                credits = "QQI Level 6 Award";
            } else if (moduleName.equals("Animal Grooming") && course.equals("Advanced Animal Science")){
                moduleCode = "6N6226";
                courseCode = "6M5153";
                credits = "QQI Level 6 Award";
            } else if (moduleName.equals("Communications") && course.equals("Advanced Animal Science")){
                moduleCode = "6N1950";
                courseCode = "6M5153";
                credits = "QQI Level 6 Award";
            } else if (moduleName.equals("Kennel and Cattery Management")){
                moduleCode = "6N5585";
                courseCode = "6M5153";
                credits = "QQI Level 6 Award";
            } else if (moduleName.equals("Canine Obedience and Training")){
                moduleCode = " 6N6228";
                courseCode = "6M5153";
                credits = "QQI Level 6 Award";
            } else if (moduleName.equals("Work Experience") && course.equals("Advanced Animal Science")){
                moduleCode = "6N1946";
                courseCode = "6M5153";
                credits = "QQI Level 6 Award";
            } else if (moduleName.equals("Animal Behaviour")){
                moduleCode = "6N5568";
                courseCode = "6M5153";
                credits = "QQI Level 6 Award";
            } else if (moduleName.equals("Humans, Animals and Society")){
                moduleCode = "6N5569";
                courseCode = "6M5153";
                credits = "QQI Level 6 Award";
            } 
            
           
             
            try {
                 // connect to database
                Connection con = DriverManager.getConnection(url + dbName, userName, password);
                // check to see if teacher with this first name and surname has already been added to database
                String SQL2 = "SELECT firstName, surname FROM teacher where firstName = ? and surname = ?";
                PreparedStatement prest2 = con.prepareStatement(SQL2);
                prest2.setString(1, t.getFirstName());
                prest2.setString(2, t.getSurname());
                ResultSet rs2 = prest2.executeQuery();
                // if teacher has not already been added proceed
                if (!(rs2.next())) {
                     // check to see if a teacher has already been assigned to this module
                    String SQL3 = "SELECT moduleCode FROM module WHERE moduleCode = ? ";
                    PreparedStatement prest3 = con.prepareStatement(SQL3);
                    prest3.setString(1, moduleCode);
                   
                    
                    ResultSet rs3 = prest3.executeQuery();
                    // if teacher has not already been assigned proceed
                    if (!(rs3.next())) {

                // insert module data and teacherid into module
                String SQLM = "INSERT INTO module (moduleCode, courseCode, teacherID, moduleName, credits) VALUES (?,?,?,?,?)";
                 // get max teacherID in the database
                String SQLMax = "SELECT MAX(teacherID) FROM gtirecords.teacher";
                // insert teacher data into database
                String SQL = "INSERT INTO teacher (teacherID, firstName, surname, email, PPSN, DOB, address1, address2, County, Eircode, PhoneNumber ) VALUES (?,?,?,?,?,?,?,?,?,?,?)";
                
                
                PreparedStatement prestMax = con.prepareStatement(SQLMax);
                

                ResultSet rs = prestMax.executeQuery();
                // add one to max id and assign result as new teachers id
                while (rs.next()) {
                    t.setTeacherID((rs.getInt(1) + 1));
                    jTextFieldTeacherID.setText(t.getTeacherID() + "");
                    System.out.println(rs.getInt(1));
                }

                PreparedStatement prest = con.prepareStatement(SQL);

                prest.setInt(1, t.getTeacherID());
                prest.setString(2, t.getFirstName());
                prest.setString(3, t.getSurname());
                prest.setString(4, t.getEmail());
                prest.setString(5, t.getPPSN());
                prest.setString(6, t.getDOB());
                prest.setString(7, t.getAddressL1());
                prest.setString(8, t.getAddressL2());
                prest.setString(9, t.getCounty());
                prest.setString(10, t.getEircode());
                prest.setInt(11, t.getPhoneNumber());
                System.out.println("1");
                prest.executeUpdate();
                System.out.println("2");
                 PreparedStatement prestM = con.prepareStatement(SQLM);
                
                prestM.setString(1, moduleCode);
                prestM.setString(2, courseCode);
                prestM.setInt(3, t.getTeacherID());
                prestM.setString(4, t.getModule());
                prestM.setString(5, credits);
                System.out.println("3");
                prestM.executeUpdate();
                System.out.println("4");
                // message declaring new teacher has been added
                JOptionPane.showMessageDialog(null, "New teacher " + t.getFirstName() + " " + t.getSurname() + " has been added!");

                prest.close();
                prestM.close();
                prestMax.close();
                prest2.close();
                con.close();
                
                    }else {
                  JOptionPane.showMessageDialog(null, "This module already has a teacher!");  
                }
                       
                } else {
                  JOptionPane.showMessageDialog(null, "This teacher already exists in the database!");  
                }

            } catch (SQLException err) {

                System.out.println(err.getMessage());

            }
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        //if teacher id textfield is empty tell user to search or add teacher first
        if (!(jTextFieldTeacherID.getText().equals(""))) {
            //create teacher object and assign values
            Teacher t2 = new Teacher();
            t2.setFirstName(jTextFieldFName.getText());
            t2.setSurname(jTextFieldSurname.getText());
            t2.setTeacherID(Integer.parseInt(jTextFieldTeacherID.getText()));
              // ask user if they want to delete the current record
            int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete " + t2.getFirstName() + " " + t2.getSurname() + " from "
                    + "your records?");

            if (confirm == 0) {
                System.out.println("confirming delete");

                try {
                    //connect to database
                    System.out.println("Connecting to  database" + dbName + "...");
                    Connection conn = DriverManager.getConnection(url + dbName, userName, password);
                    System.out.println("Connected database successfully...");

                    PreparedStatement prest;
                    PreparedStatement prestM;
                    PreparedStatement prestQ;
                    PreparedStatement prestB;
                    PreparedStatement prestL;
                    PreparedStatement prestF;
                    
                    String sqlB = "SELECT moduleCode FROM module WHERE teacherID = ?";
                     prestB = conn.prepareStatement(sqlB);
                    prestB.setInt(1, t2.getTeacherID());
                    
                    
                    ResultSet rs = prestB.executeQuery();
            // if teacher id is in database set all teacher info in the textfields
            while (rs.next()) {
                t2.setModule(rs.getString(1));
                
            
            
            String sqlF = "SELECT assignmentID FROM assesmnet WHERE moduleCode = ?";
                     prestF = conn.prepareStatement(sqlF);
                    prestF.setString(1, t2.getModule());
                    
                    
                    ResultSet rsF = prestF.executeQuery();
            // if teacher id is in database set all teacher info in the textfields
            while (rsF.next()) {
                
                assignmntID = rsF.getInt(1);
            
                   
                
                    
                    
                     String sqlL = "DELETE FROM student_has_assesmnet WHERE assignmentID = ?";
                    prestL = conn.prepareStatement(sqlL);
                    prestL.setInt(1, assignmntID);
                    prestL.executeUpdate();
                    
                    String sqlQ = "DELETE FROM assesmnet WHERE assignmentID = ?";
                    prestQ = conn.prepareStatement(sqlQ);
                    prestQ.setInt(1, assignmntID);
                    prestQ.executeUpdate();
                    
                    // delete everything from table with this teacherId
                    String sqlM = "DELETE FROM module WHERE teacherID = ?";
                    // delete everything from table with this teacherId
                    String sql = "DELETE FROM teacher WHERE teacherID = ?";
                    
                    prestM = conn.prepareStatement(sqlM);
                    prestM.setInt(1, t2.getTeacherID());
                    prestM.executeUpdate();

                    prest = conn.prepareStatement(sql);
                    prest.setInt(1, t2.getTeacherID());
                    prest.executeUpdate();
            
                    
                    prestM.close();
                    prest.close();
                    conn.close();
            }
            }
                } catch (SQLException err) {

                    System.out.println(err.getMessage());
                }

                clear();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please Add or search for a Teacher first!");
        }

    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed

        if (!(jTextFieldTeacherID.getText().equals(""))) {
            
            Teacher t1 = new Teacher(Integer.parseInt(jTextFieldTeacherID.getText()), jTextFieldFName.getText(), jTextFieldSurname.getText(), jTextFieldEmail.getText(), jTextFieldPPSN.getText(), jTextFieldDOB.getText(), jTextFieldAL1.getText(), jTextFieldAL2.getText(), jComboBoxCounty.getSelectedItem().toString(), jTextFieldEircode.getText(), Integer.parseInt(jTextFieldPN.getText()), jComboBoxModule.getSelectedItem().toString());

            int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to update " + t1.getFirstName() + " " + t1.getSurname() + " 's Record? ");

            if (confirm == 0) {
            try {

                Connection con = DriverManager.getConnection(url + dbName, userName, password);
                System.out.println("connected");
                
                
                  // update teacher information
                String SQL = "UPDATE TEACHER SET firstName = ?,surname = ?, email = ?,PPSN = ?, DOB =?, address1 = ?, address2 = ?, County = ?, Eircode = ?, PhoneNumber = ? WHERE teacherID = ?;";
                
                PreparedStatement prest = con.prepareStatement(SQL);

               
                prest.setString(1, t1.getFirstName());
                prest.setString(2, t1.getSurname());
                prest.setString(3, t1.getEmail());
                prest.setString(4, t1.getPPSN());
                prest.setString(5, t1.getDOB());
                prest.setString(6, t1.getAddressL1());
                prest.setString(7, t1.getAddressL2());
                prest.setString(8, t1.getCounty());
                prest.setString(9, t1.getEircode());
                prest.setInt(10, t1.getPhoneNumber());
                prest.setInt(11, t1.getTeacherID());

                prest.executeUpdate();

                JOptionPane.showMessageDialog(null, "Teacher " + t1.getFirstName() + " " + t1.getSurname() + " has been updated!");

                prest.close();
                
                con.close();
            } catch (SQLException err) {

                System.out.println(err.getMessage());

            }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please Add or search for a Teacher first!");
        }
        

    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
       // open logout frame and close current 1
        loginFrame LF = new loginFrame();
        LF.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        clear();
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jComboBoxCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCourseActionPerformed
       // when jcomboboxcourse index chnages add respective class groups to jcomboboxmodule
        int index = jComboBoxCourse.getSelectedIndex();
        if (index == 0) {
            jComboBoxModule.removeAllItems();
            jComboBoxModule.addItem("Project Management");
            jComboBoxModule.addItem("Object Oriented Programming");
            jComboBoxModule.addItem("Software Architecture");
            jComboBoxModule.addItem("Graphical User Interface Programming");
            jComboBoxModule.addItem("Leadership");
            jComboBoxModule.addItem("Work Experience");
            jComboBoxModule.addItem("Mathematics");
            jComboBoxModule.addItem("Relational Database");
            jComboBoxModule.addItem("Mobile Technologies");
            jComboBoxModule.setEnabled(true);
        } else if (index == 1) {

            jComboBoxModule.removeAllItems();
            jComboBoxModule.addItem("Animal Anatomy and Physiology");
            jComboBoxModule.addItem("Animal Welfare");
            jComboBoxModule.addItem("Animal Grooming");
            jComboBoxModule.addItem("Veterinary Assisting Skills");
            jComboBoxModule.addItem("Communications");
            jComboBoxModule.addItem("Work Experience");
            jComboBoxModule.addItem("Word Processing");
            jComboBoxModule.addItem("Safety & Health at Work");
            jComboBoxModule.setEnabled(true);
        } else if (index == 2) {

            jComboBoxModule.removeAllItems();
            jComboBoxModule.addItem("Emergency Department Care Skills");
            jComboBoxModule.addItem("Care Provision & Practice");
            jComboBoxModule.addItem("Infection Prevention and Control");
            jComboBoxModule.addItem("Care of the Older Person");
            jComboBoxModule.addItem("Anatomy & Physiology");
            jComboBoxModule.addItem("Safety and Health at Work");
            jComboBoxModule.addItem("Word Processing");
            jComboBoxModule.addItem("Communications");
            jComboBoxModule.addItem("Work Experience");
            jComboBoxModule.setEnabled(true);
        } else if (index == 3) {

            jComboBoxModule.removeAllItems();
            jComboBoxModule.addItem("Programming & Design Principles");
            jComboBoxModule.addItem("Fundamentals of OOP");
            jComboBoxModule.addItem("Software Architecture");
            jComboBoxModule.addItem("Maths for Information Technology");
            jComboBoxModule.addItem("Team working");
            jComboBoxModule.addItem("Database Methods");
            jComboBoxModule.addItem("Communications");
            jComboBoxModule.addItem("Work Experience");
            jComboBoxModule.addItem("Mobile Technologies");
            jComboBoxModule.setEnabled(true);
        } else if (index == 4) {

            jComboBoxModule.removeAllItems();
            jComboBoxModule.addItem("Animal Science and Health");
            jComboBoxModule.addItem("Communications");
            jComboBoxModule.addItem("Work Experience");
            jComboBoxModule.addItem("Animal Grooming");
            jComboBoxModule.addItem("Kennel and Cattery Management");
            jComboBoxModule.addItem("Canine Obedience and Training");
            jComboBoxModule.addItem("Animal Behaviour");
            jComboBoxModule.addItem("Humans, Animals and Society");
            jComboBoxModule.setEnabled(true);
        }

    }//GEN-LAST:event_jComboBoxCourseActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        if (!(jTextFieldSearch.getText().equals(""))) {
            
        Teacher t = new Teacher();
        t.setTeacherID(Integer.parseInt(jTextFieldSearch.getText()));

        try {

            Connection con = DriverManager.getConnection(url + dbName, userName, password);

            System.out.println("connected");
            //get module name and course code from modulee with respective teacherid
            String SQLM = "SELECT moduleName, courseCode FROM module WHERE teacherID=?";
            
            PreparedStatement prestM = con.prepareStatement(SQLM);
            
            prestM.setInt(1, t.getTeacherID());
            
            ResultSet rsm = prestM.executeQuery();
            
            if (rsm.next()){
                t.setModule(rsm.getString(1));
                courseCode = rsm.getString(2);
            }
              // get everything from teacher table with respective teacherID       
            String SQL = "SELECT * FROM teacher WHERE teacherID=?";

            PreparedStatement prest = con.prepareStatement(SQL);

            prest.setInt(1, t.getTeacherID());

            ResultSet rs = prest.executeQuery();
            // if teacher id is in database set all teacher info in the textfields
            if (rs.next()) {

                t.setFirstName(rs.getString(2));
                t.setSurname(rs.getString(3));
                t.setEmail(rs.getString(4));
                t.setPPSN(rs.getString(5));
                t.setDOB(rs.getString(6));
                t.setAddressL1(rs.getString(7));
                t.setAddressL2(rs.getString(8));
                t.setCounty(rs.getString(9));
                t.setEircode(rs.getString(10));
                t.setPhoneNumber(Integer.parseInt(rs.getString(11)));
                jTextFieldTeacherID.setText(Integer.toString(t.getTeacherID()));
                jTextFieldFName.setText(t.getFirstName());
                jTextFieldSurname.setText(t.getSurname());
                jTextFieldEmail.setText(t.getEmail());
                jTextFieldPPSN.setText(t.getPPSN());
                jTextFieldDOB.setText(t.getDOB());
                jTextFieldAL1.setText(t.getAddressL1());
                jTextFieldAL2.setText(t.getAddressL2());
                jComboBoxCounty.setSelectedItem(t.getCounty());
                jTextFieldEircode.setText(t.getEircode());
                jTextFieldPN.setText("0" + Integer.toString(t.getPhoneNumber()));
                
                // select index of jcomboboxcourse in accordance to the value of course
                if (courseCode.equals("5M0529")) {
                    jComboBoxCourse.setSelectedIndex(3);

                }
                if (courseCode.equals("5M2768")){
                    jComboBoxCourse.setSelectedIndex(1);

                }
                if (courseCode.equals("5M4468")) {
                    jComboBoxCourse.setSelectedIndex(2);

                }
                if  (courseCode.equals("6M0691")) {
                    jComboBoxCourse.setSelectedIndex(0);

                }
                if (courseCode.equals("6M5153")) {
                    jComboBoxCourse.setSelectedIndex(4);

                }
                   //set module to module stored in database
                  jComboBoxModule.setSelectedItem(t.getModule());
                  jComboBoxCourse.setEnabled(false);
                  jComboBoxModule.setEnabled(false);
                

            } else {
                JOptionPane.showMessageDialog(null, "No Teacher by that ID in the database!");
            }

            prest.close();
            prestM.close();
            con.close();

        } catch (SQLException err) {

            System.out.println(err.getMessage());

        }

        } else {
            JOptionPane.showMessageDialog(null, "Please enter a Teacher ID first!");
        }


    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void jTextFieldSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchKeyTyped
        char keyTyped = evt.getKeyChar();
        String search = jTextFieldSearch.getText();
        // validation digits only
        if (!(Character.isDigit(keyTyped))) {

            evt.consume();

        }
        // only allow 6 digits
        if (search.length() > 5) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldSearchKeyTyped

    private void jButtonAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddMouseEntered
       // when mouse enters add button change colour to white
        jButtonAdd.setBackground(Color.WHITE);
  
    }//GEN-LAST:event_jButtonAddMouseEntered

    private void jButtonAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddMouseExited
       // when mouse exits add button change colour to delete buttons background
        jButtonAdd.setBackground(jButtonDelete.getBackground());

    }//GEN-LAST:event_jButtonAddMouseExited

    private void jButtonDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDeleteMouseEntered
         // when mouse enters delete button change colour to white
        jButtonDelete.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButtonDeleteMouseEntered

    private void jButtonDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDeleteMouseExited
       // when mouse exits delete button change colour to add buttons background
        jButtonDelete.setBackground(jButtonAdd.getBackground());
    }//GEN-LAST:event_jButtonDeleteMouseExited

    private void jButtonUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUpdateMouseEntered
       // when mouse enters update button change colour to white
        jButtonUpdate.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButtonUpdateMouseEntered

    private void jButtonUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUpdateMouseExited
      // when mouse exits update button change colour to delete buttons background
        jButtonUpdate.setBackground(jButtonDelete.getBackground());
    }//GEN-LAST:event_jButtonUpdateMouseExited

    private void jButtonLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLogoutMouseEntered
        // when mouse enters logout button change colour to white
        jButtonLogout.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButtonLogoutMouseEntered

    private void jButtonLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLogoutMouseExited
       // when mouse exits logout button change colour to delete buttons background
        jButtonLogout.setBackground(jButtonDelete.getBackground());
    }//GEN-LAST:event_jButtonLogoutMouseExited

    private void jButtonStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStudentActionPerformed
      //open studeent frame
        adminStudentFrame ASF = new adminStudentFrame();
        ASF.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonStudentActionPerformed

    private void jButtonReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReportsActionPerformed
       //open reports frame
        reportsFrame RF = new reportsFrame();
        RF.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonReportsActionPerformed

    private void jTextFieldDOBFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDOBFocusGained
        jTextFieldDOB.setText("00/00/0000");
    }//GEN-LAST:event_jTextFieldDOBFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminTeacherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminTeacherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminTeacherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminTeacherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminTeacherFrame().setVisible(true);
            }
        });
    }
    // is slash method that checks if a charachter is a slash
    public static boolean isSlash(char c) {

        boolean hasDot = false;

        if (c == '/') {

            hasDot = true;

        } else {

            hasDot = false;

        }

        return hasDot;

    }
    // clear method that clears all the textfields
    public void clear() {
        jTextFieldTeacherID.setText("");
        jTextFieldDOB.setText("");
        jTextFieldEircode.setText("");
        jTextFieldFName.setText("");
        jTextFieldSurname.setText("");
        jTextFieldPPSN.setText("");
        jTextFieldAL1.setText("");
        jTextFieldAL2.setText("");
        jTextFieldEmail.setText("");
        jTextFieldPN.setText("");
        jComboBoxCourse.setSelectedIndex(0);
        jComboBoxCounty.setSelectedIndex(0);
        jComboBoxCourse.setEnabled(true);
        
    }
    
  
       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonReports;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonStudent;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox<String> jComboBoxCounty;
    private javax.swing.JComboBox<String> jComboBoxCourse;
    private javax.swing.JComboBox<String> jComboBoxModule;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldAL1;
    private javax.swing.JTextField jTextFieldAL2;
    private javax.swing.JTextField jTextFieldDOB;
    private javax.swing.JTextField jTextFieldEircode;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFName;
    private javax.swing.JTextField jTextFieldPN;
    private javax.swing.JTextField jTextFieldPPSN;
    private javax.swing.JTextField jTextFieldSearch;
    private javax.swing.JTextField jTextFieldSurname;
    private javax.swing.JTextField jTextFieldTeacherID;
    // End of variables declaration//GEN-END:variables
}
