/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.RecordKeeping;

import java.sql.*;

import javax.swing.*;
import java.awt.*;


/**
 *
 * @author ryan3
 */
public class adminStudentFrame extends javax.swing.JFrame {

    String url = "jdbc:mysql://127.0.0.1:3306/";
    //database name
    String dbName = "GTIRecords";

    //username for connecting to local host
    String userName = "root";
    //password for connecting to local host
    String password = "452012";

    
    /**
     * Creates new form teacherFrame
     */
    public adminStudentFrame() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonAdd = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jTextFieldSearch = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldStudentID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldFName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldSurname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldPPSN = new javax.swing.JTextField();
        jTextFieldDOB = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldAL1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldAL2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldEircode = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldPN = new javax.swing.JTextField();
        jButtonClear = new javax.swing.JButton();
        jComboBoxCounty = new javax.swing.JComboBox<>();
        jButtonClose = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxClassCode = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jComboBoxCourse = new javax.swing.JComboBox<>();
        jButtonTeacher = new javax.swing.JButton();
        jButtonReports = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Student");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.setForeground(new java.awt.Color(204, 0, 0));

        jButtonAdd.setBackground(new java.awt.Color(153, 153, 153));
        jButtonAdd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonAdd.setText("Add");
        jButtonAdd.setToolTipText("Add Student ");
        jButtonAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonAddMouseExited(evt);
            }
        });
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonDelete.setBackground(new java.awt.Color(153, 153, 153));
        jButtonDelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonDelete.setText("Delete");
        jButtonDelete.setToolTipText("Delete Student");
        jButtonDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonDeleteMouseExited(evt);
            }
        });
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonUpdate.setBackground(new java.awt.Color(153, 153, 153));
        jButtonUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonUpdate.setText("Update");
        jButtonUpdate.setToolTipText("Update Student");
        jButtonUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonUpdateMouseExited(evt);
            }
        });
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonLogout.setBackground(new java.awt.Color(153, 153, 153));
        jButtonLogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonLogout.setText("Logout");
        jButtonLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonLogoutMouseExited(evt);
            }
        });
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTextFieldSearch.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jTextFieldSearch.setToolTipText("Search via Student ID");
        jTextFieldSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSearchKeyTyped(evt);
            }
        });

        jButtonSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Student ID:");

        jTextFieldStudentID.setEditable(false);
        jTextFieldStudentID.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldStudentID.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jTextFieldStudentID.setEnabled(false);
        jTextFieldStudentID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldStudentIDKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("First Name:");

        jTextFieldFName.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jTextFieldFName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldFNameKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Surname:");

        jTextFieldSurname.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jTextFieldSurname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSurnameKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Email:");

        jTextFieldEmail.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jTextFieldEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEmailKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("PPSN:");

        jTextFieldPPSN.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jTextFieldPPSN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPPSNKeyTyped(evt);
            }
        });

        jTextFieldDOB.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jTextFieldDOB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldDOBFocusGained(evt);
            }
        });
        jTextFieldDOB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDOBKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("DOB:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Address Line 1:");

        jTextFieldAL1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jTextFieldAL1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldAL1KeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Adress Line 2:");

        jTextFieldAL2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jTextFieldAL2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldAL2KeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("County:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Eircode:");

        jTextFieldEircode.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jTextFieldEircode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEircodeKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Phone Number:");

        jTextFieldPN.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jTextFieldPN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPNKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPNKeyTyped(evt);
            }
        });

        jButtonClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jComboBoxCounty.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jComboBoxCounty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Antrim", "Armagh", "Carlow", "Cavan", "Clare", "Cork", "Derry", "Donegal", "Down", "Dublin", "Fermanagh", "Galway", "Kerry", "Kildare", "Kilkenny", "Laois", "Leitrim", "Limerick", "Longford", "Louth", "Mayo", "Meath", "Monaghan", "Offaly", "Roscommon", "Sligo", "Tipperary", "Tyrone", "Waterford", "Westmeath", "Wexford", "Wicklow" }));

        jButtonClose.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Class Code:");

        jComboBoxClassCode.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jComboBoxClassCode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PSD1", "PSD2", "PSD3" }));
        jComboBoxClassCode.setEnabled(false);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Course:");

        jComboBoxCourse.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jComboBoxCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Programming and Software Development", "Dog Grooming", "Emergency Care Services", "Advanced Software Development", "Advanced Animal Science" }));
        jComboBoxCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCourseActionPerformed(evt);
            }
        });

        jButtonTeacher.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonTeacher.setText("Add Teacher");
        jButtonTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTeacherActionPerformed(evt);
            }
        });

        jButtonReports.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonReports.setText("Reports");
        jButtonReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReportsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldFName, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldPPSN, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldAL1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldAL2, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxCounty, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldEircode, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonClose))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButtonTeacher)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonReports)
                                .addGap(49, 49, 49)
                                .addComponent(jButtonClear))
                            .addComponent(jTextFieldPN)
                            .addComponent(jComboBoxClassCode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxCourse, 0, 379, Short.MAX_VALUE))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldPPSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldAL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldAL2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBoxCounty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldEircode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jComboBoxCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jComboBoxClassCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClose)
                    .addComponent(jButtonClear)
                    .addComponent(jButtonTeacher)
                    .addComponent(jButtonReports))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSearch)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldStudentIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldStudentIDKeyTyped
        // Validation -  only digits allowed
        char keyTyped = evt.getKeyChar();
       
        if (!(Character.isDigit(keyTyped))) {

            evt.consume();

        }
    }//GEN-LAST:event_jTextFieldStudentIDKeyTyped

    private void jTextFieldFNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFNameKeyTyped
        // Validation -  only letters allowed
        char keyTyped = evt.getKeyChar();

        if (!(Character.isLetter(keyTyped))) {

            evt.consume();

        }
    }//GEN-LAST:event_jTextFieldFNameKeyTyped

    private void jTextFieldSurnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSurnameKeyTyped
        // Validation -  only letters allowed
        char keyTyped = evt.getKeyChar();

        if (!(Character.isLetter(keyTyped))) {

            evt.consume();

        }
    }//GEN-LAST:event_jTextFieldSurnameKeyTyped

    private void jTextFieldEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEmailKeyTyped
        // Validation -  spaces not allowed
        char keyTyped = evt.getKeyChar();

        if (Character.isSpace(keyTyped)) {

            evt.consume();

        }
    }//GEN-LAST:event_jTextFieldEmailKeyTyped

    private void jTextFieldPPSNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPPSNKeyTyped
        // Validation -  only letters and digits allowed
        char keyTyped = evt.getKeyChar();
        String PPSN = jTextFieldPPSN.getText();

        if (!(Character.isLetterOrDigit(keyTyped))) {

            evt.consume();

        }
        //if ppsn is bigger than 8 charachters long consume charachter
        if (PPSN.length() > 7) {
            evt.consume();
        }

    }//GEN-LAST:event_jTextFieldPPSNKeyTyped

    private void jTextFieldDOBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDOBKeyTyped
//         Validation -  only digits allowed and slashes
        char keyTyped = evt.getKeyChar();
        String DOB = jTextFieldDOB.getText();

        if (!(Character.isDigit(keyTyped) || isSlash(keyTyped))) {

            evt.consume();

        }
//if ppsn is bigger than 10 charachters long consume charachter
        if (DOB.length() > 9) {
            evt.consume();
        }

    }//GEN-LAST:event_jTextFieldDOBKeyTyped

    private void jTextFieldAL1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAL1KeyTyped
        // Validation -  only letters, digits and spaces allowed
        char keyTyped = evt.getKeyChar();

        if (!(Character.isLetterOrDigit(keyTyped) || Character.isSpace(keyTyped))) {

            evt.consume();

        }
    }//GEN-LAST:event_jTextFieldAL1KeyTyped

    private void jTextFieldAL2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAL2KeyTyped
        // Validation -  only letters, digits and spaces allowed
        char keyTyped = evt.getKeyChar();

        if (!(Character.isLetterOrDigit(keyTyped) || Character.isSpace(keyTyped))) {

            evt.consume();

        }
    }//GEN-LAST:event_jTextFieldAL2KeyTyped

    private void jTextFieldEircodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEircodeKeyTyped
        // Validation -  only letters, digits and spaces allowed
        char keyTyped = evt.getKeyChar();
        String eircode = jTextFieldEircode.getText();
        if (!(Character.isLetterOrDigit(keyTyped))) {

            evt.consume();

        }
//if ppsn is bigger than 7 charachters long consume charachter
        if (eircode.length() > 6) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldEircodeKeyTyped

    private void jTextFieldPNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPNKeyTyped
        // Validation -  only digits allowed
        char keyTyped = evt.getKeyChar();
        String PN = jTextFieldPN.getText();

        if (!(Character.isDigit(keyTyped))) {

            evt.consume();

        }

        // if phone number is bigger than 10 digits consume charachter
        if (PN.length() > 9) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldPNKeyTyped

    private void jTextFieldPNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPNKeyReleased
        String PN = jTextFieldPN.getText();
        //if phone number dosent start with 0 consume
        if (!(PN.startsWith("0"))) {
            evt.consume();
            jTextFieldPN.setText("");
        }
    }//GEN-LAST:event_jTextFieldPNKeyReleased

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        dispose();

    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // declareing variables for validation purposes below 
        String DOB = jTextFieldDOB.getText();
        String eircode = jTextFieldEircode.getText();
        String fName = jTextFieldFName.getText();
        String sName = jTextFieldSurname.getText();
        String PPSN = jTextFieldPPSN.getText();
        String address = jTextFieldAL1.getText();
        String address2 = jTextFieldAL2.getText();
        String email = jTextFieldEmail.getText();
        String phoneNumber = jTextFieldPN.getText();

        //if first name is not entered give error message
        if (fName.length() == 0) {
            JOptionPane.showMessageDialog(null, "Please Enter your First Name!");
            jTextFieldFName.setText("");

            //if surname is not entered give error message  
        } else if (sName.length() == 0) {
            JOptionPane.showMessageDialog(null, "Please Enter your Surname!");
            jTextFieldSurname.setText("");

            //if email is not enetered correctly give error message
        } else if (!(email.contains("@") && email.contains("."))) {
            JOptionPane.showMessageDialog(null, "Invalid format email needs @ and .");
            jTextFieldEmail.setText("");
            
            // if ppsn is less than 8 charachters give error message
        } else if (PPSN.length() < 8) {
            JOptionPane.showMessageDialog(null, "PPSN must be 8 charachters");
            jTextFieldPPSN.setText("");

            //if dob is not enetered give error message
        } else if (DOB.length() < 10) {
            JOptionPane.showMessageDialog(null, "Please Enter your Date of Birth!");
            jTextFieldDOB.setText("");
            
            // if address is too short give error message
        } else if (address.length() < 5) {
            JOptionPane.showMessageDialog(null, "Please Enter your full Address!");
            jTextFieldAL1.setText("");

            // if address is too short give error message
        } else if (address2.length() < 5) {
            JOptionPane.showMessageDialog(null, "Please Enter your full Address!");
            jTextFieldAL2.setText("");

            //  if eircode is not enetered give error message
        } else if (eircode.length() < 7) {
            JOptionPane.showMessageDialog(null, "Please Enter valid Eircode!");
            jTextFieldEircode.setText("");

            //  if phone number is not enetered give error message
        } else if (phoneNumber.length() < 10) {
            JOptionPane.showMessageDialog(null, "Phone number must be 10 digits");
            jTextFieldPN.setText("");

           
        } else {
            // create student object and set student varaibles
            Student s = new Student(0, jTextFieldFName.getText(), jTextFieldSurname.getText(), jTextFieldEmail.getText(), jTextFieldPPSN.getText(), jTextFieldDOB.getText(), jTextFieldAL1.getText(), jTextFieldAL2.getText(), jComboBoxCounty.getSelectedItem().toString(), jTextFieldEircode.getText(), Integer.parseInt(jTextFieldPN.getText()), jComboBoxClassCode.getSelectedItem().toString());

            try {
                // connect to database
                Connection con = DriverManager.getConnection(url + dbName, userName, password);
                // check to see if student with this first name and surname has already been added to database
                String SQL2 = "SELECT firstName, surname FROM student where firstName = ? and surname = ?";
                PreparedStatement prest2 = con.prepareStatement(SQL2);
                prest2.setString(1, s.getFirstName());
                prest2.setString(2, s.getSurname());
                ResultSet rs2 = prest2.executeQuery();
                // if student has not already been added proceed
                if (!(rs2.next())) {
                // get max studentID in the database
                String SQLMax = "SELECT MAX(studentID) FROM gtirecords.student;";
                // insert student data into database
                String SQL = "INSERT INTO student (studentID, classGroupCode, firstName, surname, email, PPSN, DOB, address1, address2, County, Eircode, PhoneNumber ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)";

                PreparedStatement prestMax = con.prepareStatement(SQLMax);

                ResultSet rs = prestMax.executeQuery();
                // add one to max id and assign result as new students id
                while (rs.next()) {
                    s.setStudentID((rs.getInt(1) + 1));
                    jTextFieldStudentID.setText(s.getStudentID() + "");
                    System.out.println(rs.getInt(1));
                }

                PreparedStatement prest = con.prepareStatement(SQL);

                prest.setInt(1, s.getStudentID());
                prest.setString(2, s.getClassCode());
                prest.setString(3, s.getFirstName());
                prest.setString(4, s.getSurname());
                prest.setString(5, s.getEmail());
                prest.setString(6, s.getPPSN());
                prest.setString(7, s.getDOB());
                prest.setString(8, s.getAddressL1());
                prest.setString(9, s.getAddressL2());
                prest.setString(10, s.getCounty());
                prest.setString(11, s.getEircode());
                prest.setInt(12, s.getPhoneNumber());

                prest.executeUpdate();
                // message declaring new student has been added
                JOptionPane.showMessageDialog(null, "New student " + s.getFirstName() + " " + s.getSurname() + " has been added!");

                prest.close();
                prestMax.close();
                con.close();
                
                } else {
                    JOptionPane.showMessageDialog(null, "This student already exists in the database!");
                }

            } catch (SQLException err) {

                System.out.println(err.getMessage());

            }
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        //if student id textfield is empty tell user to search or add student first
        if (!(jTextFieldStudentID.getText().equals(""))) {

            Student s2 = new Student();
            s2.setFirstName(jTextFieldFName.getText());
            s2.setSurname(jTextFieldSurname.getText());
            s2.setStudentID(Integer.parseInt(jTextFieldStudentID.getText()));

          
            int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete " + s2.getFirstName() + " " + s2.getSurname() + " from "
                    + "your records?");

            if (confirm == 0) {
                System.out.println("confirming delete");

                try {
                    //connect to database
                    System.out.println("Connecting to  database" + dbName + "...");
                    Connection conn = DriverManager.getConnection(url + dbName, userName, password);
                    System.out.println("Connected database successfully...");
                    
                    PreparedStatement prest1;
                    // delete everything from table with this studentId
                    String sql1 = "DELETE FROM student_has_assesmnet WHERE studentID = ?";

                    prest1 = conn.prepareStatement(sql1);
                    prest1.setInt(1, s2.getStudentID());
                    prest1.executeUpdate();

                    PreparedStatement prest;
                    //delete everything from table with this studentId
                    String sql = "DELETE FROM student WHERE studentID = ?";

                    prest = conn.prepareStatement(sql);
                    prest.setInt(1, s2.getStudentID());
                    prest.executeUpdate();

                    prest.close();
                    conn.close();

                } catch (SQLException err) {

                    System.out.println(err.getMessage());
                }

                clear();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please Add or search for a student first!");
        }

    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed

        if (!(jTextFieldStudentID.getText().equals(""))) {

            Student s1 = new Student(Integer.parseInt(jTextFieldStudentID.getText()), jTextFieldFName.getText(), jTextFieldSurname.getText(), jTextFieldEmail.getText(), jTextFieldPPSN.getText(), jTextFieldDOB.getText(), jTextFieldAL1.getText(), jTextFieldAL2.getText(), jComboBoxCounty.getSelectedItem().toString(), jTextFieldEircode.getText(), Integer.parseInt(jTextFieldPN.getText()), jComboBoxClassCode.getSelectedItem().toString());

            int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to update " + s1.getFirstName() + " " + s1.getSurname() + " 's Record? ");

            if (confirm == 0) {
            try {

                Connection con = DriverManager.getConnection(url + dbName, userName, password);
                System.out.println("connected");
                // update student information
                String SQL = "UPDATE STUDENT SET classGroupCode = ?, firstName = ?,surname = ?, email = ?,PPSN = ?, DOB =?, address1 = ?, address2 = ?, County = ?, Eircode = ?, PhoneNumber = ? WHERE studentID = ?;";

                PreparedStatement prest = con.prepareStatement(SQL);

                prest.setString(1, s1.getClassCode());
                prest.setString(2, s1.getFirstName());
                prest.setString(3, s1.getSurname());
                prest.setString(4, s1.getEmail());
                prest.setString(5, s1.getPPSN());
                prest.setString(6, s1.getDOB());
                prest.setString(7, s1.getAddressL1());
                prest.setString(8, s1.getAddressL2());
                prest.setString(9, s1.getCounty());
                prest.setString(10, s1.getEircode());
                prest.setInt(11, s1.getPhoneNumber());
                prest.setInt(12, s1.getStudentID());

                prest.executeUpdate();

                JOptionPane.showMessageDialog(null, "Student " + s1.getFirstName() + " " + s1.getSurname() + " has been updated!");

                prest.close();
                con.close();
            } catch (SQLException err) {

                System.out.println(err.getMessage());

            }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please Add or search for a student first!");
        }
        

    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        //open login frame and close current frame
        loginFrame LF = new loginFrame();
        LF.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        clear();
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jComboBoxCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCourseActionPerformed
        // when jcomboboxcourse index chnages add respective class groups to jcomboboxclasscode
        int index = jComboBoxCourse.getSelectedIndex();
        if (index == 0) {
            jComboBoxClassCode.removeAllItems();
            jComboBoxClassCode.addItem("PSD1");
            jComboBoxClassCode.addItem("PSD2");
            jComboBoxClassCode.addItem("PSD3");
            jComboBoxClassCode.setEnabled(true);
        } else if (index == 1) {

            jComboBoxClassCode.removeAllItems();
            jComboBoxClassCode.addItem("DG1");
            jComboBoxClassCode.addItem("DG2");
            jComboBoxClassCode.addItem("DG3");
            jComboBoxClassCode.setEnabled(true);
        } else if (index == 2) {

            jComboBoxClassCode.removeAllItems();
            jComboBoxClassCode.addItem("ECS1");
            jComboBoxClassCode.addItem("ECS2");
            jComboBoxClassCode.addItem("ECS3");
            jComboBoxClassCode.setEnabled(true);
        } else if (index == 3) {

            jComboBoxClassCode.removeAllItems();
            jComboBoxClassCode.addItem("ASD1");
            jComboBoxClassCode.addItem("ASD2");
            jComboBoxClassCode.addItem("ASD3");
            jComboBoxClassCode.setEnabled(true);
        } else if (index == 4) {

            jComboBoxClassCode.removeAllItems();
            jComboBoxClassCode.addItem("AAS1");
            jComboBoxClassCode.addItem("AAS2");
            jComboBoxClassCode.addItem("AAS3");
            jComboBoxClassCode.setEnabled(true);
        }

    }//GEN-LAST:event_jComboBoxCourseActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        if (!(jTextFieldSearch.getText().equals(""))) {
            
        Student s = new Student();
        s.setStudentID(Integer.parseInt(jTextFieldSearch.getText()));

        try {

            Connection con = DriverManager.getConnection(url + dbName, userName, password);

            System.out.println("connected");
            // get everything from student table with respeective studentID
            String SQL = "SELECT * FROM student WHERE studentID=?";

            PreparedStatement prest = con.prepareStatement(SQL);

            prest.setInt(1, s.getStudentID());

            ResultSet rs = prest.executeQuery();
            // if student id is in database set all student info in the textfields
            if (rs.next()) {

                s.setClassCode(rs.getString(2));
                s.setFirstName(rs.getString(3));
                s.setSurname(rs.getString(4));
                s.setEmail(rs.getString(5));
                s.setPPSN(rs.getString(6));
                s.setDOB(rs.getString(7));
                s.setAddressL1(rs.getString(8));
                s.setAddressL2(rs.getString(9));
                s.setCounty(rs.getString(10));
                s.setEircode(rs.getString(11));
                s.setPhoneNumber(Integer.parseInt(rs.getString(12)));
                jTextFieldStudentID.setText(Integer.toString(s.getStudentID()));
                jTextFieldFName.setText(s.getFirstName());
                jTextFieldSurname.setText(s.getSurname());
                jTextFieldEmail.setText(s.getEmail());
                jTextFieldPPSN.setText(s.getPPSN());
                jTextFieldDOB.setText(s.getDOB());
                jTextFieldAL1.setText(s.getAddressL1());
                jTextFieldAL2.setText(s.getAddressL2());
                jComboBoxCounty.setSelectedItem(s.getCounty());
                jTextFieldEircode.setText(s.getEircode());
                jTextFieldPN.setText("0" + Integer.toString(s.getPhoneNumber()));
                
                 // select index of jcomboboxcourse in accordance to the value of class code
        String CC = s.getClassCode();

        if (CC.equals("PSD1") || CC.equals("PSD2") || CC.equals("PSD3")) {
            jComboBoxCourse.setSelectedIndex(0);

        }
        if (CC.equals("DG1") || CC.equals("DG2") || CC.equals("DG3")) {
            jComboBoxCourse.setSelectedIndex(1);

        }
        if (CC.equals("ECS1") || CC.equals("ECS2") || CC.equals("ECS3")) {
            jComboBoxCourse.setSelectedIndex(2);

        }
        if (CC.equals("ASD1") || CC.equals("ASD2") || CC.equals("ASD3")) {
            jComboBoxCourse.setSelectedIndex(3);

        }
        if (CC.equals("AAS1") || CC.equals("AAS2") || CC.equals("AAS3")) {
            jComboBoxCourse.setSelectedIndex(4);

        }
        jComboBoxClassCode.setSelectedItem(s.getClassCode());
                
            } else {
                JOptionPane.showMessageDialog(null, "No student by that ID in the database!");
            }

            prest.close();
            con.close();

        } catch (SQLException err) {

            System.out.println(err.getMessage());

        }
       
        
        } else {
            JOptionPane.showMessageDialog(null, "Please enter a student ID first!");
        }


    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void jTextFieldSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchKeyTyped
      
        char keyTyped = evt.getKeyChar();
        String search = jTextFieldSearch.getText();
        // validation digits only
        if (!(Character.isDigit(keyTyped))) {

            evt.consume();

        }
        // only allow 6 digits
        if (search.length() > 5) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldSearchKeyTyped

    private void jButtonAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddMouseEntered
       // when mouse enters add button change colour to white
        jButtonAdd.setBackground(Color.WHITE);
  
    }//GEN-LAST:event_jButtonAddMouseEntered

    private void jButtonAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddMouseExited
       // when mouse exits add button change colour to delete buttons background
        jButtonAdd.setBackground(jButtonDelete.getBackground());


    }//GEN-LAST:event_jButtonAddMouseExited

    private void jButtonDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDeleteMouseEntered
        // when mouse enters delete button change colour to white
        jButtonDelete.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButtonDeleteMouseEntered

    private void jButtonDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDeleteMouseExited
      // when mouse exits delete button change colour to add buttons background
        jButtonDelete.setBackground(jButtonAdd.getBackground());
    }//GEN-LAST:event_jButtonDeleteMouseExited

    private void jButtonUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUpdateMouseEntered
       // when mouse enters update button change colour to white
        jButtonUpdate.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButtonUpdateMouseEntered

    private void jButtonUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUpdateMouseExited
       // when mouse exits update button change colour to delete buttons background
        jButtonUpdate.setBackground(jButtonDelete.getBackground());
    }//GEN-LAST:event_jButtonUpdateMouseExited

    private void jButtonLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLogoutMouseEntered
      // when mouse enters logout button change colour to white
        jButtonLogout.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButtonLogoutMouseEntered

    private void jButtonLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLogoutMouseExited
        // when mouse exits logout button change colour to delete buttons background
        jButtonLogout.setBackground(jButtonDelete.getBackground());
    }//GEN-LAST:event_jButtonLogoutMouseExited

    private void jButtonTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTeacherActionPerformed
       //open teacher frame
        adminTeacherFrame ATF = new adminTeacherFrame();
        ATF.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonTeacherActionPerformed

    private void jButtonReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReportsActionPerformed
       //open reports frame
        reportsFrame RF = new reportsFrame();
        RF.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonReportsActionPerformed

    private void jTextFieldDOBFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDOBFocusGained
        jTextFieldDOB.setText("00/00/0000");
    }//GEN-LAST:event_jTextFieldDOBFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminStudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminStudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminStudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminStudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminStudentFrame().setVisible(true);
            }
        });
    }
    // is slash method that checks if a charachter is a slash
    public static boolean isSlash(char c) {

        boolean hasDot = false;

        if (c == '/') {

            hasDot = true;

        } else {

            hasDot = false;

        }

        return hasDot;

    }
    // clear method that clears all the textfields
    public void clear() {
        jTextFieldStudentID.setText("");
        jTextFieldDOB.setText("");
        jTextFieldEircode.setText("");
        jTextFieldFName.setText("");
        jTextFieldSurname.setText("");
        jTextFieldPPSN.setText("");
        jTextFieldAL1.setText("");
        jTextFieldAL2.setText("");
        jTextFieldEmail.setText("");
        jTextFieldPN.setText("");
        jComboBoxCourse.setSelectedIndex(0);
        jComboBoxCounty.setSelectedIndex(0);
    }
    
  
       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonReports;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonTeacher;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox<String> jComboBoxClassCode;
    private javax.swing.JComboBox<String> jComboBoxCounty;
    private javax.swing.JComboBox<String> jComboBoxCourse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldAL1;
    private javax.swing.JTextField jTextFieldAL2;
    private javax.swing.JTextField jTextFieldDOB;
    private javax.swing.JTextField jTextFieldEircode;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFName;
    private javax.swing.JTextField jTextFieldPN;
    private javax.swing.JTextField jTextFieldPPSN;
    private javax.swing.JTextField jTextFieldSearch;
    private javax.swing.JTextField jTextFieldStudentID;
    private javax.swing.JTextField jTextFieldSurname;
    // End of variables declaration//GEN-END:variables
}
