/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.RecordKeeping;

import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;



/**
 *
 * @author ryan3
 */
public class reportsFrame extends javax.swing.JFrame {
    
    String url = "jdbc:mysql://127.0.0.1:3306/";
    //database name
    String dbName = "GTIRecords";

    //username for connecting to local host
    String userName = "root";
    //password for connecting to local host
    String password = "452012";
    
    // declare public variables for use in the reports 
    public static String examClassCode = "";
    public static String classCode = "";
     public static String result = "";
    public static int assignmentID = 0;
    public static int counter = -1;
    public static String ModuleName = "";
    public static String moduleCode = "";

    /**
     * Creates new form reportsFrame
     */
    public reportsFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableStudent = new javax.swing.JTable();
        jTextFieldSearch1 = new javax.swing.JTextField();
        jButtonSearchCG = new javax.swing.JButton();
        jTextFieldSearchD = new javax.swing.JTextField();
        jButtonSearchD = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldLR = new javax.swing.JTextField();
        jTextFieldResultsCG = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonResults = new javax.swing.JButton();
        jButtonLR = new javax.swing.JButton();
        jTextFieldResultsM = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonClose = new javax.swing.JButton();
        jButtonlogout = new javax.swing.JButton();
        jButtonPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reports");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jTableStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "First Name", "Surname", "StudentID", "Email", "PPSN", "DOB", "Address1", "Address2", "County", "Eircode", "Phone Number", "Module", "Assignment 1", "Assignment 2", "Exam", "Result", "Class Group"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableStudent);

        jTextFieldSearch1.setToolTipText("Enter Class Group");
        jTextFieldSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearch1ActionPerformed(evt);
            }
        });
        jTextFieldSearch1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSearch1KeyTyped(evt);
            }
        });

        jButtonSearchCG.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonSearchCG.setText("Search");
        jButtonSearchCG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchCGActionPerformed(evt);
            }
        });

        jTextFieldSearchD.setToolTipText("Enter Module name");
        jTextFieldSearchD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSearchDKeyTyped(evt);
            }
        });

        jButtonSearchD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonSearchD.setText("Search");
        jButtonSearchD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchDActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Class Group Information");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Distinction Students for Certain module");

        jTextFieldLR.setToolTipText("Enter Student Surname");
        jTextFieldLR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldLRKeyTyped(evt);
            }
        });

        jTextFieldResultsCG.setToolTipText("Enter Class Group");
        jTextFieldResultsCG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldResultsCGKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Full Learner Record");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Class Group results for Ceratin module");

        jButtonResults.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonResults.setText("Search");
        jButtonResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResultsActionPerformed(evt);
            }
        });

        jButtonLR.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonLR.setText("Search");
        jButtonLR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLRActionPerformed(evt);
            }
        });

        jTextFieldResultsM.setToolTipText("Enter Module");
        jTextFieldResultsM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldResultsMKeyTyped(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Class Group");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Module");

        jButtonClose.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jButtonlogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonlogout.setText("Logout");
        jButtonlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonlogoutActionPerformed(evt);
            }
        });

        jButtonPrint.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonPrint.setText("Print");
        jButtonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1488, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldSearchD, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSearchD))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldLR, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonLR))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1)
                                            .addComponent(jTextFieldSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonSearchCG))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(jTextFieldResultsCG))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jTextFieldResultsM, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButtonResults))
                                            .addComponent(jLabel6))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonClose))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(jButtonPrint)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonlogout)))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldSearchD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonSearchD))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonSearchCG)
                        .addComponent(jButtonlogout)
                        .addComponent(jButtonPrint)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldResultsCG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonResults)
                    .addComponent(jButtonLR)
                    .addComponent(jTextFieldResultsM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonClose))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSearchCGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchCGActionPerformed
      //If search textfield isnt empty proceed
        if (!(jTextFieldSearch1.getText().equals(""))) {
            // if
            if(jTextFieldSearch1.getText().equalsIgnoreCase("PSD1") || jTextFieldSearch1.getText().equalsIgnoreCase("PSD2") || jTextFieldSearch1.getText().equalsIgnoreCase("PSD3") || jTextFieldSearch1.getText().equalsIgnoreCase("AAS1") || jTextFieldSearch1.getText().equalsIgnoreCase("AAS2") || jTextFieldSearch1.getText().equalsIgnoreCase("AAS3") || jTextFieldSearch1.getText().equalsIgnoreCase("DG1") || jTextFieldSearch1.getText().equalsIgnoreCase("DG2") || jTextFieldSearch1.getText().equalsIgnoreCase("DG3") || jTextFieldSearch1.getText().equalsIgnoreCase("ECS1") || jTextFieldSearch1.getText().equalsIgnoreCase("ECS2") || jTextFieldSearch1.getText().equalsIgnoreCase("ECS3") || jTextFieldSearch1.getText().equalsIgnoreCase("ASD1") || jTextFieldSearch1.getText().equalsIgnoreCase("ASD2") || jTextFieldSearch1.getText().equalsIgnoreCase("ASD3")) {
            classCode = jTextFieldSearch1.getText();
        Student s = new Student();
        s.setClassCode(jTextFieldSearch1.getText());
// clear the jtable
        for (int ii = 0; ii < 24; ii++) {
                            
                            jTableStudent.setValueAt("", ii, 0);
                            jTableStudent.setValueAt("" ,ii, 1);
                            jTableStudent.setValueAt("", ii, 2);
                            jTableStudent.setValueAt("", ii, 3);
                            jTableStudent.setValueAt("", ii, 4);
                            jTableStudent.setValueAt("", ii, 5);
                            jTableStudent.setValueAt("", ii, 6);
                            jTableStudent.setValueAt("", ii, 7);
                            jTableStudent.setValueAt("", ii, 8);
                            jTableStudent.setValueAt("", ii, 9);
                            jTableStudent.setValueAt("", ii, 10);
                            jTableStudent.setValueAt("", ii, 11);
                            jTableStudent.setValueAt("", ii, 12);
                            jTableStudent.setValueAt("", ii, 13);
                            jTableStudent.setValueAt("", ii, 14);
                            jTableStudent.setValueAt("", ii, 15);
                            jTableStudent.setValueAt("", ii, 16);
                            
        }
        

        try {
            
            Connection con = DriverManager.getConnection(url + dbName, userName, password);

            System.out.println("connected");
            // get student info from class code
            String SQL = "SELECT studentID, firstName, surname, email, PPSN, DOB, address1, address2, County, Eircode, PhoneNumber FROM student WHERE classGroupCode = ?";

            PreparedStatement prest = con.prepareStatement(SQL);

            prest.setString(1, s.getClassCode());
            

            ResultSet rs = prest.executeQuery();

            while (rs.next()) {
                System.out.println(1);
                s.setStudentID(rs.getInt(1));
                s.setFirstName(rs.getString(2));
                s.setSurname(rs.getString(3));
                s.setEmail(rs.getString(4));
                s.setPPSN(rs.getString(5));
                s.setDOB(rs.getString(6));
                s.setAddressL1(rs.getString(7));
                s.setAddressL2(rs.getString(8));
                s.setCounty(rs.getString(9));
                s.setEircode(rs.getString(10));
                s.setPhoneNumber(rs.getInt(11));
                    // assign course code
                     if (s.getClassCode().equals("PSD1") || s.getClassCode().equals("PSD2") || s.getClassCode().equals("PSD3")) {
                     examClassCode = "5M0529";

                         }
                      if (s.getClassCode().equals("DG1") || s.getClassCode().equals("DG2") || s.getClassCode().equals("DG3")) {
                      examClassCode = "5M2768";

                         }
                       if (s.getClassCode().equals("ECS1") || s.getClassCode().equals("ECS2") || s.getClassCode().equals("ECS3")) {
                           examClassCode = "5M4468";

                           }
                      if (s.getClassCode().equals("ASD1") || s.getClassCode().equals("ASD2") || s.getClassCode().equals("ASD3")) {
                           examClassCode = "6M0691";

                          }
                       if (s.getClassCode().equals("AAS1") || s.getClassCode().equals("AAS2") || s.getClassCode().equals("AAS3")) {
                          examClassCode = "6M5153";

                          }
                    
                     
                        counter++;
                        // populate jtable
                        for (int i = 0; i < 1; i++) {
                            
                            jTableStudent.setValueAt(s.getFirstName(), counter, 0);
                            jTableStudent.setValueAt(s.getSurname() ,counter, 1);
                            jTableStudent.setValueAt(s.getStudentID(), counter, 2);
                            jTableStudent.setValueAt(s.getEmail(), counter, 3);
                            jTableStudent.setValueAt(s.getPPSN(), counter, 4);
                            jTableStudent.setValueAt(s.getDOB(), counter, 5);
                            jTableStudent.setValueAt(s.getAddressL1(), counter, 6);
                            jTableStudent.setValueAt(s.getAddressL2(), counter, 7);
                            jTableStudent.setValueAt(s.getCounty(), counter, 8);
                            jTableStudent.setValueAt(s.getEircode(), counter, 9);
                            jTableStudent.setValueAt("0" + s.getPhoneNumber(), counter, 10);
                            jTableStudent.setValueAt(classCode, counter, 16);
                         
                        }
            } 
            
            counter = -1;
            prest.close();
            con.close();
                
            
        } catch (SQLException err) {

            System.out.println(err.getMessage());

        }
            } else {
               JOptionPane.showMessageDialog(null, "Please enter a valid Class Group!"); 
            }
        }else {
            JOptionPane.showMessageDialog(null, "Please enter Class Group first!");
        }
    }                                                    

    private void jButtonAddJTableActionPerformed(java.awt.event.ActionEvent evt) {                                                 

    }//GEN-LAST:event_jButtonSearchCGActionPerformed

    private void jTextFieldSearch1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearch1KeyTyped
       char keyTyped = evt.getKeyChar();
        

        if (!(Character.isLetterOrDigit(keyTyped))) {

            evt.consume();

        }
        
         String S1 =jTextFieldSearch1.getText();
        
       
        
          if (S1.length() > 3) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldSearch1KeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
         
    }//GEN-LAST:event_formWindowActivated

    private void jButtonSearchDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchDActionPerformed
         if (!(jTextFieldSearchD.getText().equals(""))) {
             // validation for module
             if (jTextFieldSearchD.getText().equalsIgnoreCase("Fundamentals of OOP") || jTextFieldSearchD.getText().equalsIgnoreCase("Communications") || jTextFieldSearchD.getText().equalsIgnoreCase("Animal Anatomy and Physiology") || jTextFieldSearchD.getText().equalsIgnoreCase("Word Processing") || jTextFieldSearchD.getText().equalsIgnoreCase("Software Architecture") ||  jTextFieldSearchD.getText().equalsIgnoreCase("Work Experience") || jTextFieldSearchD.getText().equalsIgnoreCase("Object Oriented Programming") || jTextFieldSearchD.getText().equalsIgnoreCase("Mathematics") || jTextFieldSearchD.getText().equalsIgnoreCase("Project Management") || jTextFieldSearchD.getText().equalsIgnoreCase("Humans, Animals and Society")){
       
            ModuleName = jTextFieldSearchD.getText();
            Student s = new Student();
        
        //clear table
        for (int ii = 0; ii < 24; ii++) {
                            
                            jTableStudent.setValueAt("", ii, 0);
                            jTableStudent.setValueAt("" ,ii, 1);
                            jTableStudent.setValueAt("", ii, 2);
                            jTableStudent.setValueAt("", ii, 3);
                            jTableStudent.setValueAt("", ii, 4);
                            jTableStudent.setValueAt("", ii, 5);
                            jTableStudent.setValueAt("", ii, 6);
                            jTableStudent.setValueAt("", ii, 7);
                            jTableStudent.setValueAt("", ii, 8);
                            jTableStudent.setValueAt("", ii, 9);
                            jTableStudent.setValueAt("", ii, 10);
                            jTableStudent.setValueAt("", ii, 11);
                            jTableStudent.setValueAt("", ii, 12);
                            jTableStudent.setValueAt("", ii, 13);
                            jTableStudent.setValueAt("", ii, 14);
                            jTableStudent.setValueAt("", ii, 15);
                            jTableStudent.setValueAt("", ii, 16);
                            
        }
        
        try {
            
            Connection con = DriverManager.getConnection(url + dbName, userName, password);

            System.out.println("connected");
            // get module code
            String SQL = "SELECT moduleCode FROM module WHERE moduleName like ?";

            PreparedStatement prest = con.prepareStatement(SQL);

            prest.setString(1, ModuleName);
            
            ResultSet rs = prest.executeQuery();
            
            while (rs.next()) {
                
                moduleCode = (rs.getString(1));
                    // get student grades for distinction students
                          String SQLM = "SELECT assesmnet.assignment1, assesmnet.assignment2, assesmnet.exam, assesmnet.result, assesmnet.assignmentID FROM assesmnet WHERE assesmnet.moduleCode = ? AND assesmnet.result > 79 ";

                          PreparedStatement prestM = con.prepareStatement(SQLM);
                
                          prestM.setString(1, moduleCode);
                         
                         ResultSet rsM = prestM.executeQuery();
                         
                          s.setAssignment1(0);
                          s.setAssignment2(0);
                          s.setExam(0);
                          s.setTotal(0);
                          
                          result = "N/A";

                        while (rsM.next()) {
                          s.setAssignment1(rsM.getInt(1));
                          s.setAssignment2(rsM.getInt(2));
                          s.setExam(rsM.getInt(3));
                          s.setTotal(rsM.getInt(4));
                          assignmentID = (rsM.getInt(5));
                           int total = s.getTotal();
                            result = "";
                    if (total > 79){
                        result = "Distinction!";
                    } else if (total > 64){
                        result = "Merit!";
                    } else if (total > 49){
                        result = "Pass";
                    } else if (total > 0){
                        result = "unsucessful";
                    } else {
                        result = "N/A";
                    }
                        // get students id
                        String SQLS = "SELECT studentID from student_has_assesmnet WHERE assignmentID = ? ";

                          PreparedStatement prestS = con.prepareStatement(SQLS);
                
                          prestS.setInt(1, assignmentID);
                          
                          ResultSet rsS = prestS.executeQuery();
                          
                          while (rsS.next()) {
                              s.setStudentID(rsS.getInt(1));
                              
                          }
                          // get students full name from id
                          String SQL2 = "SELECT firstName, surname, classGroupCode from student WHERE studentID = ? ";

                          PreparedStatement prest2 = con.prepareStatement(SQL2);
               
                          prest2.setInt(1, s.getStudentID());
                          
                          ResultSet rs2 = prest2.executeQuery();
                          
                          while (rs2.next()) {
                              s.setFirstName(rs2.getString(1));
                              s.setSurname(rs2.getString(2));
                              s.setClassCode(rs2.getString(3));
                              
                          }
                         
                        counter++;
                       //populate table
                        for (int i = 0; i < 1; i++) {
                            
                            jTableStudent.setValueAt(s.getFirstName(), counter, 0);
                            jTableStudent.setValueAt(s.getSurname() ,counter, 1);
                            jTableStudent.setValueAt(ModuleName, counter, 11);
                            jTableStudent.setValueAt(s.getAssignment1(), counter, 12);
                            jTableStudent.setValueAt(s.getAssignment2(), counter, 13);
                            jTableStudent.setValueAt(s.getExam(), counter, 14);
                            jTableStudent.setValueAt(result, counter, 15);
                            jTableStudent.setValueAt(s.getClassCode(), counter, 16);
                            
                        }
                        }
                        
            } 
            
            counter = -1;
            prest.close();
            
            con.close();
                
            
        } catch (SQLException err) {

            System.out.println(err.getMessage());

        }
             }else {
            JOptionPane.showMessageDialog(null, "Please enter Valid Module!");
        }
        }else {
            JOptionPane.showMessageDialog(null, "Please enter Module first!");
        }
    }//GEN-LAST:event_jButtonSearchDActionPerformed

    private void jTextFieldSearchDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchDKeyTyped
           char keyTyped = evt.getKeyChar();
        

        if (!(Character.isLetter(keyTyped) || isSpace(keyTyped))) {

            evt.consume();

        }
    }//GEN-LAST:event_jTextFieldSearchDKeyTyped

    private void jTextFieldSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSearch1ActionPerformed

    private void jButtonLRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLRActionPerformed
        if (!(jTextFieldLR.getText().equals(""))) {
           
            
        Student s = new Student();
        s.setSurname(jTextFieldLR.getText());
        
        //clear table
        for (int ii = 0; ii < 24; ii++) {
                            
                            jTableStudent.setValueAt("", ii, 0);
                            jTableStudent.setValueAt("" ,ii, 1);
                            jTableStudent.setValueAt("", ii, 2);
                            jTableStudent.setValueAt("", ii, 3);
                            jTableStudent.setValueAt("", ii, 4);
                            jTableStudent.setValueAt("", ii, 5);
                            jTableStudent.setValueAt("", ii, 6);
                            jTableStudent.setValueAt("", ii, 7);
                            jTableStudent.setValueAt("", ii, 8);
                            jTableStudent.setValueAt("", ii, 9);
                            jTableStudent.setValueAt("", ii, 10);
                            jTableStudent.setValueAt("", ii, 11);
                            jTableStudent.setValueAt("", ii, 12);
                            jTableStudent.setValueAt("", ii, 13);
                            jTableStudent.setValueAt("", ii, 14);
                            jTableStudent.setValueAt("", ii, 15);
                            jTableStudent.setValueAt("", ii, 16);
                            
                            
                            
        }
        

        try {
            
            Connection con = DriverManager.getConnection(url + dbName, userName, password);
            // get student info using like wildcard 
            String SQL = "SELECT studentID, classGroupCode, firstName, surname FROM student WHERE surname LIKE ?";

            PreparedStatement prest = con.prepareStatement(SQL);

            prest.setString(1, s.getSurname() + "%");
            
            ResultSet rs = prest.executeQuery();

            if (rs.next()) {
                
                s.setStudentID((rs.getInt(1)));
                s.setClassCode((rs.getString(2)));
                s.setFirstName((rs.getString(3)));
                s.setSurname((rs.getString(4)));
                    //get assignment id for grades
                         String SQLS = "SELECT assignmentID from student_has_assesmnet WHERE studentID = ? ";

                          PreparedStatement prestS = con.prepareStatement(SQLS);
                
               
                          prestS.setInt(1, s.getStudentID());
                          
                          ResultSet rsS = prestS.executeQuery();
                          
                          while (rsS.next()) {
                              assignmentID = (rsS.getInt(1));
                             // get student grades
                          String SQLM = "SELECT assesmnet.assignment1, assesmnet.assignment2, assesmnet.exam, assesmnet.result, assesmnet.moduleCode FROM assesmnet WHERE assesmnet.assignmentID = ?";

                          PreparedStatement prestM = con.prepareStatement(SQLM);
                
                          prestM.setInt(1, assignmentID);
                         
                         ResultSet rsM = prestM.executeQuery();
                         
                          s.setAssignment1(0);
                          s.setAssignment2(0);
                          s.setExam(0);
                          s.setTotal(0);
                          moduleCode = "";
                          
                          result = "N/A";

                        while (rsM.next()) {
                          s.setAssignment1(rsM.getInt(1));
                          s.setAssignment2(rsM.getInt(2));
                          s.setExam(rsM.getInt(3));
                          s.setTotal(rsM.getInt(4));
                          moduleCode = (rsM.getString(5));
                          System.out.println(moduleCode);
                           int total = s.getTotal();
                            result = "";
                    if (total > 79){
                        result = "Distinction!";
                    } else if (total > 64){
                        result = "Merit!";
                    } else if (total > 49){
                        result = "Pass";
                    } else if (total > 0){
                        result = "unsucessful";
                    } else {
                        result = "N/A";
                    }
                    // get module name
                     String SQL3 = "SELECT moduleName from module WHERE moduleCode = ? ";

                          PreparedStatement prest3 = con.prepareStatement(SQL3);
                
               
                          prest3.setString(1, moduleCode);
                          
                          ResultSet rs3 = prest3.executeQuery();
                          
                          while (rs3.next()) {
                              ModuleName = (rs3.getString(1));
                          }
                          System.out.println(ModuleName);
                
                      
                        counter++;
                        // populate table
                        for (int i = 0; i < 1; i++) {
                            
                            jTableStudent.setValueAt(s.getFirstName(), counter, 0);
                            jTableStudent.setValueAt(s.getSurname() ,counter, 1);
                            jTableStudent.setValueAt(ModuleName, counter, 11);
                            jTableStudent.setValueAt(s.getAssignment1(), counter, 12);
                            jTableStudent.setValueAt(s.getAssignment2(), counter, 13);
                            jTableStudent.setValueAt(s.getExam(), counter, 14);
                            jTableStudent.setValueAt(result, counter, 15);
                            jTableStudent.setValueAt(s.getClassCode(), counter, 16);
                            
                          
                        }
                        }
                        }
                        
            } else {
                JOptionPane.showMessageDialog(null, "No student with this surname in the database");
            }
            
            counter = -1;
            prest.close();
            
            con.close();
                
            
        } catch (SQLException err) {

            System.out.println(err.getMessage());

        }
            
        }else {
            JOptionPane.showMessageDialog(null, "Please enter Students Surname first!");
        }
    }//GEN-LAST:event_jButtonLRActionPerformed

    private void jTextFieldLRKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLRKeyTyped
         char keyTyped = evt.getKeyChar();
        

        if (!(Character.isLetter(keyTyped))) {

            evt.consume();

        }
    }//GEN-LAST:event_jTextFieldLRKeyTyped

    private void jTextFieldResultsCGKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldResultsCGKeyTyped
       char keyTyped = evt.getKeyChar();
        

        if (!(Character.isLetterOrDigit(keyTyped))) {

            evt.consume();

        }
        
         String CG1 =jTextFieldResultsCG.getText();
        
       
        
          if (CG1.length() > 3) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldResultsCGKeyTyped

    private void jButtonResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResultsActionPerformed
       //ensure textfield isnt empty
        if (!(jTextFieldResultsCG.getText().equals(""))) {
            //ensure correct class code is entered
            if(jTextFieldResultsCG.getText().equalsIgnoreCase("PSD1") || jTextFieldResultsCG.getText().equalsIgnoreCase("PSD2") || jTextFieldResultsCG.getText().equalsIgnoreCase("PSD3") || jTextFieldResultsCG.getText().equalsIgnoreCase("AAS1") || jTextFieldResultsCG.getText().equalsIgnoreCase("AAS2") || jTextFieldResultsCG.getText().equalsIgnoreCase("AAS3") || jTextFieldResultsCG.getText().equalsIgnoreCase("DG1") || jTextFieldResultsCG.getText().equalsIgnoreCase("DG2") || jTextFieldResultsCG.getText().equalsIgnoreCase("DG3") || jTextFieldResultsCG.getText().equalsIgnoreCase("ECS1") || jTextFieldResultsCG.getText().equalsIgnoreCase("ECS2") || jTextFieldResultsCG.getText().equalsIgnoreCase("ECS3") || jTextFieldResultsCG.getText().equalsIgnoreCase("ASD1") || jTextFieldResultsCG.getText().equalsIgnoreCase("ASD2") || jTextFieldResultsCG.getText().equalsIgnoreCase("ASD3")) {
               //esnures textfield isnt empty
                if (!(jTextFieldResultsM.getText().equals(""))) {
                    //ensures correct module is entered
                    if (jTextFieldResultsM.getText().equalsIgnoreCase("Fundamentals of OOP") || jTextFieldResultsM.getText().equalsIgnoreCase("Communications") || jTextFieldResultsM.getText().equalsIgnoreCase("Animal Anatomy and Physiology") || jTextFieldResultsM.getText().equalsIgnoreCase("Word Processing") || jTextFieldResultsM.getText().equalsIgnoreCase("Software Architecture") ||  jTextFieldResultsM.getText().equalsIgnoreCase("Work Experience") || jTextFieldResultsM.getText().equalsIgnoreCase("Object Oriented Programming") || jTextFieldResultsM.getText().equalsIgnoreCase("Mathematics") || jTextFieldResultsM.getText().equalsIgnoreCase("Project Management") || jTextFieldResultsM.getText().equalsIgnoreCase("Humans, Animals and Society")){
           
            ModuleName = jTextFieldResultsM.getText();
            Student s = new Student();
            s.setClassCode(jTextFieldResultsCG.getText());
        // clear table
        for (int ii = 0; ii < 24; ii++) {
                            
                            jTableStudent.setValueAt("", ii, 0);
                            jTableStudent.setValueAt("" ,ii, 1);
                            jTableStudent.setValueAt("", ii, 2);
                            jTableStudent.setValueAt("", ii, 3);
                            jTableStudent.setValueAt("", ii, 4);
                            jTableStudent.setValueAt("", ii, 5);
                            jTableStudent.setValueAt("", ii, 6);
                            jTableStudent.setValueAt("", ii, 7);
                            jTableStudent.setValueAt("", ii, 8);
                            jTableStudent.setValueAt("", ii, 9);
                            jTableStudent.setValueAt("", ii, 10);
                            jTableStudent.setValueAt("", ii, 11);
                            jTableStudent.setValueAt("", ii, 12);
                            jTableStudent.setValueAt("", ii, 13);
                            jTableStudent.setValueAt("", ii, 14);
                            jTableStudent.setValueAt("", ii, 15);
                            jTableStudent.setValueAt("", ii, 16);
                            
                            
                            
        }
        

        try {
            
            Connection con = DriverManager.getConnection(url + dbName, userName, password);

            System.out.println("connected");
            // get module code
            String SQL = "SELECT moduleCode FROM module WHERE moduleName = ?";

            PreparedStatement prest = con.prepareStatement(SQL);

            prest.setString(1, ModuleName);
            

            ResultSet rs = prest.executeQuery();

            while (rs.next()) {
                
                moduleCode = (rs.getString(1));
            }
            // get student info
            String SQL2 = "SELECT studentID, firstName, surname from student WHERE classGroupCode= ? ";

                          PreparedStatement prest2 = con.prepareStatement(SQL2);
                
               
                          prest2.setString(1, s.getClassCode());
                          
                          ResultSet rs2 = prest2.executeQuery();
                          
                          while (rs2.next()) {
                              s.setStudentID(rs2.getInt(1));
                              s.setFirstName(rs2.getString(2));
                              s.setSurname(rs2.getString(3));
                              
                              
                // get student grades
                          String SQLM = "SELECT assesmnet.assignment1, assesmnet.assignment2, assesmnet.exam, assesmnet.result, assesmnet.assignmentID FROM assesmnet INNER JOIN student_has_assesmnet ON assesmnet.assignmentID = student_has_assesmnet.assignmentID WHERE assesmnet.moduleCode = ? AND student_has_assesmnet.studentID = ? ";

                          PreparedStatement prestM = con.prepareStatement(SQLM);
                
               
                          prestM.setString(1, moduleCode);
                          prestM.setInt(2, s.getStudentID());
                         
                          

                         ResultSet rsM = prestM.executeQuery();
                         
                          s.setAssignment1(0);
                          s.setAssignment2(0);
                          s.setExam(0);
                          s.setTotal(0);
                          assignmentID = 0;
                          
                          result = "N/A";

                        while (rsM.next()) {
                          s.setAssignment1(rsM.getInt(1));
                          s.setAssignment2(rsM.getInt(2));
                          s.setExam(rsM.getInt(3));
                          s.setTotal(rsM.getInt(4));
                          assignmentID = (rsM.getInt(5));
                           int total = s.getTotal();
                            result = "";
                    if (total > 79){
                        result = "Distinction!";
                    } else if (total > 64){
                        result = "Merit!";
                    } else if (total > 49){
                        result = "Pass";
                    } else if (total > 0){
                        result = "unsucessful";
                    } else {
                        result = "N/A";
                    }
                    
                     
                      
                        counter++;
                        // populate table
                        for (int i = 0; i < 1; i++) {
                            
                            jTableStudent.setValueAt(s.getFirstName(), counter, 0);
                            jTableStudent.setValueAt(s.getSurname() ,counter, 1);
                            jTableStudent.setValueAt(ModuleName, counter, 11);
                            jTableStudent.setValueAt(s.getAssignment1(), counter, 12);
                            jTableStudent.setValueAt(s.getAssignment2(), counter, 13);
                            jTableStudent.setValueAt(s.getExam(), counter, 14);
                            jTableStudent.setValueAt(result, counter, 15);
                            jTableStudent.setValueAt(s.getClassCode(), counter, 16);
                            
                          
                        }
                        }
                        }
                        
            
            
            counter = -1;
            prest.close();
            
            con.close();
                
            
        } catch (SQLException err) {

            System.out.println(err.getMessage());

        }
                    }else {
            JOptionPane.showMessageDialog(null, "Please enter Valid Module!");
                }
             }else {
            JOptionPane.showMessageDialog(null, "Please enter Module first!");
                }
            }else {
            JOptionPane.showMessageDialog(null, "Please enter Valid Class Group!");
            }
        }else {
            JOptionPane.showMessageDialog(null, "Please enter Class Group first!");
        }
    }//GEN-LAST:event_jButtonResultsActionPerformed

    private void jTextFieldResultsMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldResultsMKeyTyped
           char keyTyped = evt.getKeyChar();
        

        if (!(Character.isLetter(keyTyped) || isSpace(keyTyped))) {

            evt.consume();

        }
    }//GEN-LAST:event_jTextFieldResultsMKeyTyped

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonlogoutActionPerformed
        //open login frame and close current frame
        loginFrame LF = new loginFrame();
        LF.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonlogoutActionPerformed

    private void jButtonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintActionPerformed
          try {
              // name file
            FileWriter outFile = new FileWriter("C:/OOP/"  + "Report " + ".txt");
            PrintWriter out = new PrintWriter(outFile);
            //declare variables
            String a;
            String a1;
            String a2;
            String a3;
            String a4;
            String a5;
            String a6;
            String a7;
            String a8;
            String a9;
            String a10;
            String a11;
            String a12;
            String a13;
            String a14;
            String a15 ;
            String a16 ;
            
            
            //get info fro table
            for  (int i = 0; i < 24; i++){
                a = jTableStudent.getValueAt(i, 0).toString();
                a1 = jTableStudent.getValueAt(i, 1).toString();
                a2 = jTableStudent.getValueAt(i, 2).toString();
                a3 = jTableStudent.getValueAt(i, 3).toString();
                a4 = jTableStudent.getValueAt(i, 4).toString();
                a5 = jTableStudent.getValueAt(i, 5).toString();
                a6 = jTableStudent.getValueAt(i, 6).toString();
                a7 = jTableStudent.getValueAt(i, 7).toString();
                a9 = jTableStudent.getValueAt(i, 8).toString();
                a10 = jTableStudent.getValueAt(i, 9).toString();
                a11 = jTableStudent.getValueAt(i, 10).toString();
                a12 = jTableStudent.getValueAt(i, 11).toString();
                a13 = jTableStudent.getValueAt(i, 12).toString();
                a14 = jTableStudent.getValueAt(i, 13).toString();
                a15 = jTableStudent.getValueAt(i, 14).toString();
                a16 = jTableStudent.getValueAt(i, 15).toString();
                a8 = jTableStudent.getValueAt(i, 16).toString();
                //print to file
              out.println( a + " " + a1 +" " + a2 +" " + a3 +" " + a4 +" " + a5 +" " + a6 +" " + a7 +" " + a9 +" " + a10 +" " + a11 +" " + a12 +" " + a13 +" " + a14 +" " + a15 +" " + a16 + " " + a8);
            }
           
            
            

            out.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
        // telling user file has been created
        JOptionPane.showMessageDialog(null, "Your Text file has been created!");
    }//GEN-LAST:event_jButtonPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reportsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reportsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reportsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reportsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reportsFrame().setVisible(true);
            }
        });
    }
    
     public static boolean isSpace(char c) {

        boolean hasDot = false;

        if (c == ' ') {

            hasDot = true;

        } else {

            hasDot = false;

        }

        return hasDot;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonLR;
    private javax.swing.JButton jButtonPrint;
    private javax.swing.JButton jButtonResults;
    private javax.swing.JButton jButtonSearchCG;
    private javax.swing.JButton jButtonSearchD;
    private javax.swing.JButton jButtonlogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableStudent;
    private javax.swing.JTextField jTextFieldLR;
    private javax.swing.JTextField jTextFieldResultsCG;
    private javax.swing.JTextField jTextFieldResultsM;
    private javax.swing.JTextField jTextFieldSearch1;
    private javax.swing.JTextField jTextFieldSearchD;
    // End of variables declaration//GEN-END:variables
}
