/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.RecordKeeping;

import java.sql.*;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author ryan3
 */
public class teacherFrame extends javax.swing.JFrame {
    //connect to database
    String url = "jdbc:mysql://127.0.0.1:3306/";
    //database name
    String dbName = "GTIRecords";

    //username for connecting to local host
    String userName = "root";
    //password for connecting to local host
    String password = "452012";

    public static String moduleCode = "";
    public static String courseCode = "";
    public static int assignmentID = 0;

    /**
     * Creates new form teacherFrame
     */
    public teacherFrame() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonStudentGrades = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jTextFieldSearch = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jButtonClear = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextFieldSearchS = new javax.swing.JTextField();
        jButtonSearchS = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaStudentGrades = new javax.swing.JTextArea();
        jToggleButtonAGrades = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldTeacherID = new javax.swing.JTextField();
        jComboBoxCourse = new javax.swing.JComboBox<>();
        jComboBoxModule = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Teacher");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(255, 204, 0));
        jPanel2.setForeground(new java.awt.Color(204, 0, 0));

        jButtonStudentGrades.setBackground(new java.awt.Color(153, 153, 153));
        jButtonStudentGrades.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonStudentGrades.setText("Student Grades");
        jButtonStudentGrades.setToolTipText("Add Student ");
        jButtonStudentGrades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonStudentGradesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonStudentGradesMouseExited(evt);
            }
        });
        jButtonStudentGrades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStudentGradesActionPerformed(evt);
            }
        });

        jButtonLogout.setBackground(new java.awt.Color(153, 153, 153));
        jButtonLogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonLogout.setText("Logout");
        jButtonLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonLogoutMouseExited(evt);
            }
        });
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonStudentGrades, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonStudentGrades, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTextFieldSearch.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jTextFieldSearch.setToolTipText("Please enter Teacher ID");
        jTextFieldSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSearchKeyTyped(evt);
            }
        });

        jButtonSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jButtonClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextFieldSearchS.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jTextFieldSearchS.setToolTipText("Search for Student Via Surname");
        jTextFieldSearchS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSearchSKeyTyped(evt);
            }
        });

        jButtonSearchS.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonSearchS.setText("Search");
        jButtonSearchS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchSActionPerformed(evt);
            }
        });

        jTextAreaStudentGrades.setEditable(false);
        jTextAreaStudentGrades.setColumns(20);
        jTextAreaStudentGrades.setRows(5);
        jScrollPane2.setViewportView(jTextAreaStudentGrades);

        jToggleButtonAGrades.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jToggleButtonAGrades.setText("All Grades");
        jToggleButtonAGrades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonAGradesActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Teacher ID:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Course:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Module:");

        jTextFieldTeacherID.setEditable(false);
        jTextFieldTeacherID.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldTeacherID.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jTextFieldTeacherID.setEnabled(false);
        jTextFieldTeacherID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTeacherIDKeyTyped(evt);
            }
        });

        jComboBoxCourse.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jComboBoxCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Advanced Software Development", "Dog Grooming", "Emergency Care Services", "Programming and Software Development", "Advanced Animal Science" }));
        jComboBoxCourse.setEnabled(false);
        jComboBoxCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCourseActionPerformed(evt);
            }
        });

        jComboBoxModule.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jComboBoxModule.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Project Management", "OOP", "Software Architecture", "GUI Programming", "Leadership", "Work Experience", "Mathematics", "Relational Database", "Mobile Technologies" }));
        jComboBoxModule.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxCourse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldTeacherID, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxModule, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldTeacherID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jComboBoxCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jComboBoxModule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextFieldSearchS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSearchS)
                        .addGap(132, 132, 132))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(34, 34, 34)
                        .addComponent(jToggleButtonAGrades, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonClear)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 153, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSearchS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearchS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jToggleButtonAGrades)
                    .addComponent(jButtonClear))
                .addGap(10, 10, 10))
        );

        jScrollPane1.setViewportView(jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonStudentGradesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStudentGradesActionPerformed
       //open teacher grades frame
        teacherGradesFrame2 TGF = new teacherGradesFrame2();
        TGF.setVisible(true);
        dispose();

    }//GEN-LAST:event_jButtonStudentGradesActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
       //open login frame
        loginFrame LF = new loginFrame();
        LF.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
       //if the search textfield isnt blank proceed
        if (!(jTextFieldSearch.getText().equals(""))) {

            Teacher t = new Teacher();
            t.setTeacherID(Integer.parseInt(jTextFieldSearch.getText()));

            try {

                Connection con = DriverManager.getConnection(url + dbName, userName, password);

                System.out.println("connected");
                // get module info from teachers ID
                String SQLM = "SELECT moduleName, courseCode, moduleCode FROM module WHERE teacherID=?";

                PreparedStatement prestM = con.prepareStatement(SQLM);

                prestM.setInt(1, t.getTeacherID());

                ResultSet rsm = prestM.executeQuery();
                
                if (rsm.next()) {
                    t.setModule(rsm.getString(1));
                    courseCode = rsm.getString(2);
                    moduleCode = rsm.getString(3);
                    //set index of course combo box
                    if (courseCode.equals("6M0691")) {
                        jComboBoxCourse.setSelectedIndex(0);
                    } else if (courseCode.equals("5M2768")) {
                        jComboBoxCourse.setSelectedIndex(1);
                    } else if (courseCode.equals("5M4468")) {
                        jComboBoxCourse.setSelectedIndex(2);
                    } else if (courseCode.equals("5M0529")) {
                        jComboBoxCourse.setSelectedIndex(3);
                    } else if (courseCode.equals("6M5153")) {
                        jComboBoxCourse.setSelectedIndex(4);
                    }
                    jComboBoxModule.removeAllItems();
                    jComboBoxModule.addItem(t.getModule());
                    jComboBoxModule.setSelectedItem(t.getModule());
                    jTextFieldTeacherID.setText(Integer.toString(t.getTeacherID()));
                    
                      //make swing containers visible
                jTextFieldTeacherID.setVisible(true);
                jComboBoxCourse.setVisible(true);
                jComboBoxModule.setVisible(true);
                jLabel1.setVisible(true);
                jLabel12.setVisible(true);
                jLabel13.setVisible(true);
                
                jButtonStudentGrades.setEnabled(true);
                jTextFieldSearchS.setEnabled(true);
                jButtonSearchS.setEnabled(true);
                jTextAreaStudentGrades.setEnabled(true);
                } else {
                JOptionPane.showMessageDialog(null, "No Teacher by that ID in the database!");
            }
              
                

 
            } catch (SQLException err) {

                System.out.println(err.getMessage());

            }

        } else {
            JOptionPane.showMessageDialog(null, "Please enter a Teacher ID first!");
        }


    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void jTextFieldSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchKeyTyped
        char keyTyped = evt.getKeyChar();
        String search = jTextFieldSearch.getText();

        if (!(Character.isDigit(keyTyped))) {

            evt.consume();

        }

        if (search.length() > 5) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldSearchKeyTyped

    private void jButtonStudentGradesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonStudentGradesMouseEntered
        jButtonStudentGrades.setBackground(Color.WHITE);

    }//GEN-LAST:event_jButtonStudentGradesMouseEntered

    private void jButtonStudentGradesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonStudentGradesMouseExited
        jButtonStudentGrades.setBackground(jButtonLogout.getBackground());


    }//GEN-LAST:event_jButtonStudentGradesMouseExited

    private void jButtonLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLogoutMouseEntered
        jButtonLogout.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButtonLogoutMouseEntered

    private void jButtonLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLogoutMouseExited
        jButtonLogout.setBackground(jButtonStudentGrades.getBackground());
    }//GEN-LAST:event_jButtonLogoutMouseExited

    private void jComboBoxCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCourseActionPerformed
       
    }//GEN-LAST:event_jComboBoxCourseActionPerformed

    private void jTextFieldTeacherIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTeacherIDKeyTyped
        // Validation -  only digits allowed
        char keyTyped = evt.getKeyChar();

        if (!(Character.isDigit(keyTyped))) {

            evt.consume();

        }
    }//GEN-LAST:event_jTextFieldTeacherIDKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // set containers to invisible
        jTextFieldTeacherID.setVisible(false);
        jComboBoxCourse.setVisible(false);
        jComboBoxModule.setVisible(false);
        jLabel1.setVisible(false);
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        jButtonStudentGrades.setEnabled(false);
        jTextFieldSearchS.setEnabled(false);
        jButtonSearchS.setEnabled(false);
        jTextAreaStudentGrades.setEnabled(false);
        JOptionPane.showMessageDialog(null, "Please enter your Teacher ID in the searchbar!");        
    }//GEN-LAST:event_formWindowOpened

    private void jButtonSearchSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchSActionPerformed
        // make sure textbox isnt empty
        if (!(jTextFieldSearchS.getText().equals(""))) {

            Student s = new Student();
            s.setSurname(jTextFieldSearchS.getText());

            try {

                Connection con = DriverManager.getConnection(url + dbName, userName, password);

                System.out.println("connected");
                // get student info from surname
                String SQLS = "SELECT studentID, firstName, surname FROM student WHERE surname LIKE ?";

                PreparedStatement prestS = con.prepareStatement(SQLS);

                prestS.setString(1, s.getSurname() + "%");

                ResultSet rsS = prestS.executeQuery();

                if (rsS.next()) {
                    s.setStudentID(rsS.getInt(1));
                    s.setFirstName(rsS.getString(2));
                    s.setSurname(rsS.getString(3));
                    // get assignmentID
                    String SQLID = "SELECT assesmnet.assignmentID FROM assesmnet INNER JOIN student_has_assesmnet ON assesmnet.assignmentID = student_has_assesmnet.assignmentID  WHERE assesmnet.moduleCode = ? AND student_has_assesmnet.studentID = ?";
                    PreparedStatement prestID = con.prepareStatement(SQLID);
                    prestID.setString(1, moduleCode);
                    prestID.setInt(2, s.getStudentID());
                    ResultSet rsID = prestID.executeQuery();
                    
                    if (rsID.next()){
                        assignmentID = (rsID.getInt(1));
                        
                        prestID.close();
                        // get student grades
                String SQL = "SELECT assesmnet.assignment1, assesmnet.assignment2, assesmnet.exam, assesmnet.result, assesmnet.moduleCode FROM assesmnet INNER JOIN student_has_assesmnet ON assesmnet.assignmentID = student_has_assesmnet.assignmentID WHERE student_has_assesmnet.assignmentID = ?";

                PreparedStatement prest = con.prepareStatement(SQL);

                prest.setInt(1, assignmentID);

                ResultSet rs = prest.executeQuery();

                if (rs.next()) {
                    s.setAssignment1(rs.getInt(1));
                    s.setAssignment2(rs.getInt(2));
                    s.setExam(rs.getInt(3));
                    s.setTotal(rs.getInt(4));
                    String examModuleCode = (rs.getString(5));
                    int total = s.getTotal();
                    String result = "";
                    if (total > 79){
                        result = "Distinction!";
                    } else if (total > 64){
                        result = "Merit!";
                    } else if (total > 49){
                        result = "Pass";
                    } else if (total > 0){
                        result = "unsuccesfull";
                    } else {
                        result = "N/A";
                    }
                    // display student grades
                    if (examModuleCode.equals(moduleCode)){
                        
                        jTextAreaStudentGrades.setText("");
                        jTextAreaStudentGrades.append("Student: "+ s.getFirstName() + " " + s.getSurname()+ "\nAssignment 1: " + Integer.toString(s.getAssignment1()) + "\nAssignment 2: " + Integer.toString(s.getAssignment2()) + "\nExam: " + Integer.toString(s.getExam()) + "\nResult: " + result); 
                    } else {
                        JOptionPane.showMessageDialog(null, "This Student is not in your class!");
                    }
                   

                    

                } else {
                    JOptionPane.showMessageDialog(null, "No Results found for this student!");
                }

                prest.close();

                con.close();

                } else {
                    JOptionPane.showMessageDialog(null, "This Student is not in your class!");
                }
               
                        
                    } else {
                        JOptionPane.showMessageDialog(null, "No student by that Surname in the database!");
                    }
                    

            } catch (SQLException err) {

                System.out.println(err.getMessage());

            }

        } else {
            JOptionPane.showMessageDialog(null, "Please enter Students Surname first!");
        }
    }//GEN-LAST:event_jButtonSearchSActionPerformed

    private void jTextFieldSearchSKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchSKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSearchSKeyTyped

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        clear();
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButtonAGradesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonAGradesActionPerformed
        Student s = new Student();
            

            try {
                

                Connection con = DriverManager.getConnection(url + dbName, userName, password);

                System.out.println("connected");

             
                // get student grades
                String SQL = "SELECT  assesmnet.assignmentID, assesmnet.assignment1, assesmnet.assignment2, assesmnet.exam, assesmnet.result FROM assesmnet INNER JOIN student_has_assesmnet ON assesmnet.assignmentID = student_has_assesmnet.assignmentID WHERE assesmnet.moduleCode = ? ";

                PreparedStatement prest = con.prepareStatement(SQL);

                prest.setString(1, moduleCode);

                ResultSet rs = prest.executeQuery();
                jTextAreaStudentGrades.setText("");
                
                
              
                while (rs.next()) {
                    
                    assignmentID = (rs.getInt(1));
                    s.setAssignment1(rs.getInt(2));
                    s.setAssignment2(rs.getInt(3));
                    s.setExam(rs.getInt(4));
                    s.setTotal(rs.getInt(5));
                     // get student ID
                    String SQLID = "SELECT studentID FROM student_has_assesmnet WHERE assignmentID = ?";
                    PreparedStatement prestID = con.prepareStatement(SQLID);
                    prestID.setInt(1, assignmentID);
                    ResultSet rsID = prestID.executeQuery();
                    
                    while (rsID.next()){
                        s.setStudentID(rsID.getInt(1));
                    }
                    prestID.close();
                    // get student full name
                    String SQLS = "SELECT firstName, surname FROM student WHERE studentID = ?";

                    PreparedStatement prestS = con.prepareStatement(SQLS);

                     prestS.setInt(1, s.getStudentID());

                    ResultSet rsS = prestS.executeQuery();

                     while (rsS.next()) {
                    
                    s.setFirstName(rsS.getString(1));
                    s.setSurname(rsS.getString(2));

                } 
                prestS.close();
                    int total = s.getTotal();
                    String result = "";
                    if (total > 79){
                        result = "Distinction!";
                    } else if (total > 64){
                        result = "Merit!";
                    } else if (total > 49){
                        result = "Pass";
                    } else if (total > 0) {
                        result = "unsuccesfull";
                    } else {
                        result = "N/A";
                    }
                    // display students grades
                    jTextAreaStudentGrades.append("Student: "+ s.getFirstName() + " " + s.getSurname()+ "\nAssignment 1: " + Integer.toString(s.getAssignment1()) + "\nAssignment 2: " + Integer.toString(s.getAssignment2()) + "\nExam: " + Integer.toString(s.getExam()) + "\nResult: " + result + "\n\n");
                    
                } 
                
                
                    
               


                prest.close();
                

                con.close();
             
            } catch (SQLException err) {

                System.out.println(err.getMessage());

            }
    }//GEN-LAST:event_jToggleButtonAGradesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teacherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teacherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teacherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teacherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teacherFrame().setVisible(true);
            }
        });
    }
    // method for identifying slashes
    public static boolean isSlash(char c) {

        boolean hasDot = false;

        if (c == '/') {

            hasDot = true;

        } else {

            hasDot = false;

        }

        return hasDot;

    }

    public void clear() {
      jTextAreaStudentGrades.setText("");
     
      jTextFieldSearchS.setText("");
    }
      


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonSearchS;
    private javax.swing.JButton jButtonStudentGrades;
    private javax.swing.JComboBox<String> jComboBoxCourse;
    private javax.swing.JComboBox<String> jComboBoxModule;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaStudentGrades;
    private javax.swing.JTextField jTextFieldSearch;
    private javax.swing.JTextField jTextFieldSearchS;
    private javax.swing.JTextField jTextFieldTeacherID;
    private javax.swing.JToggleButton jToggleButtonAGrades;
    // End of variables declaration//GEN-END:variables
}
