/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.RecordKeeping;

import java.sql.*;

import javax.swing.*;
import java.awt.*;

import static my.RecordKeeping.teacherFrame.*;

/**
 *
 * @author ryan3
 */
public class teacherGradesFrame2 extends javax.swing.JFrame {
    
    String url = "jdbc:mysql://127.0.0.1:3306/";
    //database name
    String dbName = "GTIRecords";

    //username for connecting to local host
    String userName = "root";
    //password for connecting to local host
    String password = "452012";
    
    public static String examClassCode = "";
     public static String result = "";
    public static int assignmentID = 0;
    public static int counter = -1;
    
    /**
     * Creates new form teacherFrame
     */
    public teacherGradesFrame2() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonAdd = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jTextFieldSearch = new javax.swing.JTextField();
        jButtonConfirm = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldStudentID = new javax.swing.JTextField();
        jButtonClear = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButtonStudent = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldA1 = new javax.swing.JTextField();
        jTextFieldA2 = new javax.swing.JTextField();
        jTextFieldExam = new javax.swing.JTextField();
        jTextFieldResult = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableStudent = new javax.swing.JTable();
        jButtonConfirmJTable = new javax.swing.JButton();
        jTextFieldSearch1 = new javax.swing.JTextField();
        jButtonAddJTable = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Teacher");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));
        jPanel2.setForeground(new java.awt.Color(204, 0, 0));

        jButtonAdd.setBackground(new java.awt.Color(153, 153, 153));
        jButtonAdd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonAdd.setText("Add");
        jButtonAdd.setToolTipText("Add Student ");
        jButtonAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonAddMouseExited(evt);
            }
        });
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonDelete.setBackground(new java.awt.Color(153, 153, 153));
        jButtonDelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonDelete.setText("Delete");
        jButtonDelete.setToolTipText("Delete Student");
        jButtonDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonDeleteMouseExited(evt);
            }
        });
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonUpdate.setBackground(new java.awt.Color(153, 153, 153));
        jButtonUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonUpdate.setText("Update");
        jButtonUpdate.setToolTipText("Update Student");
        jButtonUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonUpdateMouseExited(evt);
            }
        });
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonLogout.setBackground(new java.awt.Color(153, 153, 153));
        jButtonLogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonLogout.setText("Logout");
        jButtonLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonLogoutMouseExited(evt);
            }
        });
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTextFieldSearch.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jTextFieldSearch.setToolTipText("Enter Students Surname");
        jTextFieldSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSearchKeyTyped(evt);
            }
        });

        jButtonConfirm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonConfirm.setText("Confirm");
        jButtonConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Student ID:");

        jTextFieldStudentID.setEditable(false);
        jTextFieldStudentID.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldStudentID.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jTextFieldStudentID.setEnabled(false);
        jTextFieldStudentID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldStudentIDKeyTyped(evt);
            }
        });

        jButtonClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jButtonClose.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Assesment 2:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Assesment 1:");

        jButtonStudent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonStudent.setText("Teacher Frame");
        jButtonStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStudentActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Exam:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Result:");

        jTextFieldA1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jTextFieldA1.setEnabled(false);
        jTextFieldA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldA1ActionPerformed(evt);
            }
        });
        jTextFieldA1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldA1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldA1KeyTyped(evt);
            }
        });

        jTextFieldA2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jTextFieldA2.setEnabled(false);
        jTextFieldA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldA2ActionPerformed(evt);
            }
        });
        jTextFieldA2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldA2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldA2KeyTyped(evt);
            }
        });

        jTextFieldExam.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jTextFieldExam.setEnabled(false);
        jTextFieldExam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldExamKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldExamKeyTyped(evt);
            }
        });

        jTextFieldResult.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldResult.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jTextFieldResult.setEnabled(false);

        jTableStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Assignment ID", "Module Code", "Assignment 1", "Assignment 2", "Exam", "Result", "First Name", "Surname"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableStudent);

        jButtonConfirmJTable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonConfirmJTable.setText("Confirm");
        jButtonConfirmJTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmJTableActionPerformed(evt);
            }
        });

        jTextFieldSearch1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jTextFieldSearch1.setToolTipText("Enter Class Group");
        jTextFieldSearch1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSearch1KeyTyped(evt);
            }
        });

        jButtonAddJTable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonAddJTable.setText("Add");
        jButtonAddJTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddJTableActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Add from Table ->");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldA1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jButtonClose)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonClear)
                                    .addComponent(jButtonStudent)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldResult, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                                            .addComponent(jTextFieldExam)
                                            .addComponent(jTextFieldA2))))))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButtonAddJTable)
                        .addGap(60, 60, 60)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextFieldSearch1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonConfirmJTable)
                        .addContainerGap())
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTextFieldA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldExam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButtonClear))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConfirmJTable)
                    .addComponent(jButtonStudent)
                    .addComponent(jButtonClose)
                    .addComponent(jButtonAddJTable))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonConfirm)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConfirm))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldStudentIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldStudentIDKeyTyped
        // Validation -  only digits allowed
        char keyTyped = evt.getKeyChar();
       
        if (!(Character.isDigit(keyTyped))) {

            evt.consume();

        }
    }//GEN-LAST:event_jTextFieldStudentIDKeyTyped

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        dispose();

    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
       // check if student has been searched
        if (!(jTextFieldStudentID.getText().equals(""))){

            Student s = new Student();
            s.setStudentID(Integer.parseInt(jTextFieldStudentID.getText()));
            try {

                Connection con = DriverManager.getConnection(url + dbName, userName, password);
                   // get student grades
                String SQLM = "SELECT assesmnet.assignment1, assesmnet.assignment2, assesmnet.exam, assesmnet.result, assesmnet.moduleCode FROM assesmnet INNER JOIN student_has_assesmnet ON assesmnet.assignmentID = student_has_assesmnet.assignmentID WHERE assesmnet.moduleCode = ? AND student_has_assesmnet.studentID = ?  ";

                PreparedStatement prestM = con.prepareStatement(SQLM);
                
                prestM.setString(1, moduleCode);
                prestM.setInt(2, s.getStudentID());

                ResultSet rsM = prestM.executeQuery();

                if (!(rsM.next())) {
                            // declareing variables for validation purposes below 
                  int A1 ;
                  int A2 ;
                  String A1S = jTextFieldA1.getText();
                  String A2S = jTextFieldA2.getText();
                  String examS = jTextFieldExam.getText();
                  int exam ;
                  String result = "";
                  int total = 0;

                  // set assesment not completed if textfield is empty
                   if (A1S.length() == 0) {

                       jTextFieldA1.setText("Assesment 1 Not Completed");
                       A1 = 0;

                   } else{
                       A1 = Integer.parseInt(jTextFieldA1.getText());

                   }   if (A2S.length() == 0) {

                       jTextFieldA2.setText("Assesment 2 not completed");
                        A2 = 0;

                   } else{
                       A2 = Integer.parseInt(jTextFieldA2.getText());

                   }   if (examS.length() == 0) {

                       jTextFieldExam.setText("Exam not completed");
                        exam = 0;

                   } else {
                       exam = Integer.parseInt(jTextFieldExam.getText());
                   }
                   total = (A1 + A2 + exam) ;
                s.setAssignment1(A1);
                s.setAssignment2(A2);
                s.setExam(exam);
                s.setTotal(total);
                
                
                if (total > 79){
                    result = "Distinction!";
                } else if (total > 64){
                    result = "Merit!";
                } else if (total > 49){
                    result = "Pass";
                } else if (total > 0){
                    result = "unsucessful";
                } else {
                    result = "N/A";
                }
                
                // get max assignment id from records and add 1
                String SQLMax = "SELECT MAX(assignmentID) FROM gtirecords.assesmnet;";
                PreparedStatement prestMax = con.prepareStatement(SQLMax);
                 ResultSet rs = prestMax.executeQuery();
                while (rs.next()) {
                    assignmentID =((rs.getInt(1) + 1));
                    
                }
                
               
                     // add student grades to database   
                String SQL = "INSERT INTO assesmnet (assignmentID, moduleCode, assignment1, assignment2, exam, result) VALUES (?,?,?,?,?,?)";
                
                PreparedStatement prest = con.prepareStatement(SQL);

                prest.setInt(1, assignmentID);
                prest.setString(2, moduleCode);
                prest.setInt(3, s.getAssignment1());
                prest.setInt(4, s.getAssignment2());
                prest.setInt(5, s.getExam());
                
                jTextFieldResult.setText(result);
                
                prest.setInt(6, total);
                

                prest.executeUpdate();
                // insert student id and assignment id into database
                 String SQLA = "INSERT INTO student_has_assesmnet (studentID, assignmentID) VALUES (?,?)";
                PreparedStatement prestA = con.prepareStatement(SQLA);
                prestA.setInt(1, s.getStudentID());
                 prestA.setInt(2, assignmentID);
                 prestA.executeUpdate();
                
                
                JOptionPane.showMessageDialog(null, "Exam Results have been Added!");

                prest.close();
                prestA.close();
                con.close();
                
                }else {
                    JOptionPane.showMessageDialog(null, "Results have already been added!");
                }
                
        
            } catch (SQLException err) {

                System.out.println(err.getMessage());

            }
            
        } else {
             JOptionPane.showMessageDialog(null, "Please Add or search for a Students results first!");
        }
        
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // check if student id textfield is empty
        if (!(jTextFieldStudentID.getText().equals(""))) {

            Student s2 = new Student();
            s2.setStudentID(Integer.parseInt(jTextFieldStudentID.getText()));
            // ask if you want to delete record from database
            int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete " + jTextFieldSearch.getText() + "'s Results from "
                    + "your records?");

            if (confirm == 0) {
                System.out.println("confirming delete");

                try {

                    System.out.println("Connecting to  database" + dbName + "...");
                    Connection conn = DriverManager.getConnection(url + dbName, userName, password);
                    System.out.println("Connected database successfully...");
                    // get assignment id
                    String SQLA = "SELECT student_has_assesmnet.assignmentID FROM student_has_assesmnet INNER JOIN assesmnet ON student_has_assesmnet.assignmentID = assesmnet.assignmentID where assesmnet.moduleCode = ? AND student_has_assesmnet.studentID = ? ";
                    PreparedStatement prestA = conn.prepareStatement(SQLA);
                    prestA.setString(1, moduleCode);
                    prestA.setInt(2, s2.getStudentID());
            

            ResultSet rsA = prestA.executeQuery();

            while (rsA.next()) {
              assignmentID = (rsA.getInt(1));
            }       // delete from database
                    String SQLID = "DELETE FROM student_has_assesmnet WHERE assignmentID = ?";
                    PreparedStatement prestID = conn.prepareStatement(SQLID);
                    prestID.setInt(1, assignmentID);
                    prestID.executeUpdate();
                    //delete student grades
                    String sql = "DELETE FROM assesmnet WHERE assignmentID = ?";
                    
                    PreparedStatement prest;
                    prest = conn.prepareStatement(sql);
                    prest.setInt(1, assignmentID);
                    prest.executeUpdate();
                    
                    
                    prest.close();
                    prestID.close();
                    conn.close();

                } catch (SQLException err) {

                    System.out.println(err.getMessage());
                }

                clear();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please Add or search for a Students results first!");
        }

    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // check if textfield is empty
        if (!(jTextFieldStudentID.getText().equals(""))) {
       

            int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to update " + jTextFieldSearch.getText() + " 's Record? ");

            if (confirm == 0) {
            try {
                
                int A1 ;
                int A2 ;
                String A1S = jTextFieldA1.getText();
                String A2S = jTextFieldA2.getText();
                String examS = jTextFieldExam.getText();
                int exam ;
                String result = "";
                int total = 0;
       
         if (A1S.length() == 0 || A1S.equalsIgnoreCase("Assesment 1 Not Completed")) {
            
            
            A1 = 0;
  
            } else{
            A1 = Integer.parseInt(jTextFieldA1.getText());
        
         }   if (A2S.length() == 0 || A2S.equalsIgnoreCase("Assesment 2 Not Completed")) {
            
            
             A2 = 0;

         } else{
            A2 = Integer.parseInt(jTextFieldA2.getText());
            
         }   if (examS.length() == 0 || examS.equalsIgnoreCase("Exam Not Completed")) {
            
            
             exam = 0;

          } else {
            exam = Integer.parseInt(jTextFieldExam.getText());
         }
        
          Student s = new Student(Integer.parseInt(jTextFieldStudentID.getText()), A1, A2, exam, total);
          
           
           total = (A1 + A2 + exam) ;
           s.setTotal(total);
           
           if (total > 79){
                    result = "Distinction!";
                } else if (total > 64){
                    result = "Merit!";
                } else if (total > 49){
                    result = "Pass";
                } else if (total > 0){
                    result = "unsuccesful";
                } else {
                    result = "N/A";
                }

                Connection con = DriverManager.getConnection(url + dbName, userName, password);
                System.out.println("connected");
                
               String SQL1 = "SELECT assignmentID FROM student_has_assesmnet where studentID = ?";
               PreparedStatement prest1 = con.prepareStatement(SQL1);
               prest1.setInt(1, s.getStudentID());
               ResultSet rs = prest1.executeQuery();

                while (rs.next()) {
                    assignmentID = (rs.getInt(1));
                    
                }
                // update grades in database
                String SQL = "UPDATE assesmnet SET assignment1 = ?, assignment2 = ?, exam = ?,result = ? WHERE assignmentID = ?";
                
                PreparedStatement prest = con.prepareStatement(SQL);
                
                prest.setInt(1, s.getAssignment1());
                prest.setInt(2, s.getAssignment2());
                prest.setInt(3, s.getExam());
                prest.setInt(4, s.getTotal());
                prest.setInt(5, assignmentID);

               
                
                prest.executeUpdate();

                JOptionPane.showMessageDialog(null, jTextFieldSearch.getText() +  " 's results have been updated!");
                jTextFieldResult.setText(result);

                prest.close();
                prest1.close();
                con.close();
            } catch (SQLException err) {

                System.out.println(err.getMessage());

            }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please Add or search for a Students results first!");
        }
        

    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        loginFrame LF = new loginFrame();
        LF.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        clear();
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmActionPerformed
       //make sure textfield isnt empty
        if (!(jTextFieldSearch.getText().equals(""))) {
            
        Student s = new Student();
        s.setSurname(jTextFieldSearch.getText());
        

        try {

            Connection con = DriverManager.getConnection(url + dbName, userName, password);

            System.out.println("connected");
            // get student id from surname
            String SQL = "SELECT studentID, classGroupCode FROM student WHERE surname LIKE ?";

            PreparedStatement prest = con.prepareStatement(SQL);

            prest.setString(1, s.getSurname() + "%");
            

            ResultSet rs = prest.executeQuery();

            if (rs.next()) {
                s.setStudentID(rs.getInt(1));
                s.setClassCode(rs.getString(2));
                // set course code from class code
                if (s.getClassCode().equals("PSD1") || s.getClassCode().equals("PSD2") || s.getClassCode().equals("PSD3")) {
               examClassCode = "5M0529";

               }
                if (s.getClassCode().equals("DG1") || s.getClassCode().equals("DG2") || s.getClassCode().equals("DG3")) {
                examClassCode = "5M2768";

               }
                      if (s.getClassCode().equals("ECS1") || s.getClassCode().equals("ECS2") || s.getClassCode().equals("ECS3")) {
                           examClassCode = "5M4468";

                }
                      if (s.getClassCode().equals("ASD1") || s.getClassCode().equals("ASD2") || s.getClassCode().equals("ASD3")) {
                           examClassCode = "6M0691";

                 }
                    if (s.getClassCode().equals("AAS1") || s.getClassCode().equals("AAS2") || s.getClassCode().equals("AAS3")) {
                          examClassCode = "6M5153";

             }
                    //if student is in teachers class
                    if (examClassCode.equals(courseCode)) {
                        //get students grade
                String SQLM = "SELECT assesmnet.assignment1, assesmnet.assignment2, assesmnet.exam, assesmnet.result, assesmnet.moduleCode FROM assesmnet INNER JOIN student_has_assesmnet ON assesmnet.assignmentID = student_has_assesmnet.assignmentID WHERE assesmnet.moduleCode = ? AND student_has_assesmnet.studentID = ?  ";

                PreparedStatement prestM = con.prepareStatement(SQLM);
                
                prestM.setString(1, moduleCode);
                prestM.setInt(2, s.getStudentID());

                ResultSet rsM = prestM.executeQuery();

                if (rsM.next()) {
                    s.setAssignment1(rsM.getInt(1));
                    s.setAssignment2(rsM.getInt(2));
                    s.setExam(rsM.getInt(3));
                    s.setTotal(rsM.getInt(4));
                    String examModuleCode = (rsM.getString(5));
                    int total = s.getTotal();
                    String result = "";
                    if (total > 79){
                        result = "Distinction!";
                    } else if (total > 64){
                        result = "Merit!";
                    } else if (total > 49){
                        result = "Pass";
                    } else if (total > 0){
                        result = "unsucessful";
                    } else {
                        result = "N/A";
                    }
                    
                        jTextFieldA1.setEnabled(true);
                         jTextFieldA2.setEnabled(true);
                          jTextFieldExam.setEnabled(true);
                        if (!(s.getAssignment1() == 0)){
                          
                       jTextFieldA1.setText(Integer.toString(s.getAssignment1()));
                       
                       jTextFieldStudentID.setText(Integer.toString(s.getStudentID()));
                       jTextFieldResult.setText(result);
                                
                        }else{
                            jTextFieldA1.setText("Assesment 1 Not Completed");
                            jTextFieldStudentID.setText(Integer.toString(s.getStudentID()));
                       jTextFieldResult.setText(result);
                        }
                     
                    
                      
                        if (!(s.getAssignment2() == 0)){
                            
                      
                       jTextFieldA2.setText(Integer.toString(s.getAssignment2()));
                       
                       jTextFieldStudentID.setText(Integer.toString(s.getStudentID()));
                       jTextFieldResult.setText(result);
                                
                        }else{
                            jTextFieldA2.setText("Assesment 2 Not Completed");
                            jTextFieldStudentID.setText(Integer.toString(s.getStudentID()));
                       jTextFieldResult.setText(result);
                        }
                   
                       
                   
                      
                        
                         if (!(s.getExam() == 0)){
                            
                      
                       jTextFieldExam.setText(Integer.toString(s.getExam()));
                       jTextFieldStudentID.setText(Integer.toString(s.getStudentID()));
                       jTextFieldResult.setText(result);
                                
                        }else{
                            jTextFieldExam.setText("Exam Not Completed");
                            jTextFieldStudentID.setText(Integer.toString(s.getStudentID()));
                       jTextFieldResult.setText(result);
                        }
                    
                } else {
                    jTextFieldStudentID.setText(Integer.toString(s.getStudentID()));
                    jTextFieldA1.setEnabled(true);
                         jTextFieldA2.setEnabled(true);
                          jTextFieldExam.setEnabled(true);
                    JOptionPane.showMessageDialog(null, "No results found for this Student");
                     jTextFieldA1.setText("");
        jTextFieldA2.setText("");
        jTextFieldExam.setText("");
        jTextFieldResult.setText("");
                }
            prest.close();
            con.close();
                }else {
                    JOptionPane.showMessageDialog(null, "This student is not in your class");
                }
                

            } else {
                JOptionPane.showMessageDialog(null, "No student by that Surname in the database!");
            }
                
            
        } catch (SQLException err) {

            System.out.println(err.getMessage());

        }
        }else {
            JOptionPane.showMessageDialog(null, "Please enter a students surname first!");
        }


    }//GEN-LAST:event_jButtonConfirmActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void jTextFieldSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchKeyTyped
        char keyTyped = evt.getKeyChar();
        

        if (!(Character.isLetter(keyTyped))) {

            evt.consume();

        }

        
    }//GEN-LAST:event_jTextFieldSearchKeyTyped

    private void jButtonAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddMouseEntered
        jButtonAdd.setBackground(Color.WHITE);
  
    }//GEN-LAST:event_jButtonAddMouseEntered

    private void jButtonAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddMouseExited
        jButtonAdd.setBackground(jButtonDelete.getBackground());


    }//GEN-LAST:event_jButtonAddMouseExited

    private void jButtonDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDeleteMouseEntered
        jButtonDelete.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButtonDeleteMouseEntered

    private void jButtonDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDeleteMouseExited
       jButtonDelete.setBackground(jButtonAdd.getBackground());
    }//GEN-LAST:event_jButtonDeleteMouseExited

    private void jButtonUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUpdateMouseEntered
        jButtonUpdate.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButtonUpdateMouseEntered

    private void jButtonUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUpdateMouseExited
        jButtonUpdate.setBackground(jButtonDelete.getBackground());
    }//GEN-LAST:event_jButtonUpdateMouseExited

    private void jButtonLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLogoutMouseEntered
        jButtonLogout.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButtonLogoutMouseEntered

    private void jButtonLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLogoutMouseExited
        jButtonLogout.setBackground(jButtonDelete.getBackground());
    }//GEN-LAST:event_jButtonLogoutMouseExited

    private void jButtonStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStudentActionPerformed
        teacherFrame TF = new teacherFrame();
        TF.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonStudentActionPerformed

    private void jTextFieldA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldA2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldA2ActionPerformed

    private void jTextFieldA1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldA1KeyTyped
        // Validation -  only digits allowed
        char keyTyped = evt.getKeyChar();
        String A1 =jTextFieldA1.getText();
        
        if (!(Character.isDigit(keyTyped))) {

            evt.consume();

        }
        
          if (A1.length() > 1) {
            evt.consume();
        }
          
          
    }//GEN-LAST:event_jTextFieldA1KeyTyped

    private void jTextFieldA2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldA2KeyTyped
        // Validation -  only digits allowed
        char keyTyped = evt.getKeyChar();
       String A2 =jTextFieldA2.getText();
        if (!(Character.isDigit(keyTyped))) {

            evt.consume();

        }
        
         if (A2.length() > 1) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldA2KeyTyped

    private void jTextFieldExamKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldExamKeyTyped
         // Validation -  only digits allowed
        char keyTyped = evt.getKeyChar();
       String exam =jTextFieldExam.getText();
        if (!(Character.isDigit(keyTyped))) {

            evt.consume();

        }
        
        if (exam.length() > 1) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldExamKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        JOptionPane.showMessageDialog(null, "Please enter Students surname or your ClassGroup in the corresponding searchbar!");  
        
    }//GEN-LAST:event_formWindowOpened

    private void jTextFieldA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldA1ActionPerformed

       
    }//GEN-LAST:event_jTextFieldA1ActionPerformed

    private void jTextFieldA1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldA1KeyReleased
        
                  String A1S = jTextFieldA1.getText();
                  int A1;
                   if (A1S.length() == 0 || A1S.length() > 2) {
                        
                   } else{
                        A1 = Integer.parseInt(jTextFieldA1.getText());
                       if(A1 < 1 || A1 > 30){
                       jTextFieldA1.setText("");
                       JOptionPane.showMessageDialog(null, "Enter a number between 1 and 30");
                            }
                   }

        
    }//GEN-LAST:event_jTextFieldA1KeyReleased

    private void jTextFieldA2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldA2KeyReleased
                  String A2S = jTextFieldA2.getText();
                  int A2;
                   if (A2S.length() == 0 || A2S.length() > 2) {
                        
                   } else{
                        A2 = Integer.parseInt(jTextFieldA2.getText());
                       if(A2 < 1 || A2 > 30){
                       jTextFieldA2.setText("");
                       JOptionPane.showMessageDialog(null, "Enter a number between 1 and 30");
                            }
                   }

    }//GEN-LAST:event_jTextFieldA2KeyReleased

    private void jTextFieldExamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldExamKeyReleased
                  String exam = jTextFieldExam.getText();
                  int examInt;
                   if (exam.length() == 0 || exam.length() > 2) {
                        
                   } else{
                        examInt = Integer.parseInt(jTextFieldExam.getText());
                       if(examInt < 1 || examInt > 40){
                       jTextFieldExam.setText("");
                       JOptionPane.showMessageDialog(null, "Enter a number between 1 and 40");
                            }
                   }


    }//GEN-LAST:event_jTextFieldExamKeyReleased

    private void jTextFieldSearch1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearch1KeyTyped
          char keyTyped = evt.getKeyChar();
        

        if (!(Character.isLetterOrDigit(keyTyped))) {

            evt.consume();

        }
        
         String S1 =jTextFieldSearch1.getText();
        
       
        
          if (S1.length() > 3) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldSearch1KeyTyped

    private void jButtonConfirmJTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmJTableActionPerformed
       // ensure textfield isnt empty
        if (!(jTextFieldSearch1.getText().equals(""))) {
            if(jTextFieldSearch1.getText().equalsIgnoreCase("PSD1") || jTextFieldSearch1.getText().equalsIgnoreCase("PSD2") || jTextFieldSearch1.getText().equalsIgnoreCase("PSD3") || jTextFieldSearch1.getText().equalsIgnoreCase("AAS1") || jTextFieldSearch1.getText().equalsIgnoreCase("AAS2") || jTextFieldSearch1.getText().equalsIgnoreCase("AAS3") || jTextFieldSearch1.getText().equalsIgnoreCase("DG1") || jTextFieldSearch1.getText().equalsIgnoreCase("DG2") || jTextFieldSearch1.getText().equalsIgnoreCase("DG3") || jTextFieldSearch1.getText().equalsIgnoreCase("ECS1") || jTextFieldSearch1.getText().equalsIgnoreCase("ECS2") || jTextFieldSearch1.getText().equalsIgnoreCase("ECS3") || jTextFieldSearch1.getText().equalsIgnoreCase("ASD1") || jTextFieldSearch1.getText().equalsIgnoreCase("ASD2") || jTextFieldSearch1.getText().equalsIgnoreCase("ASD3")) {
            
        try {
            
            Connection con = DriverManager.getConnection(url + dbName, userName, password);

            System.out.println("connected");
            
            Student s = new Student();
            s.setClassCode(jTextFieldSearch1.getText());
        //set course code
          if (s.getClassCode().equalsIgnoreCase("PSD1") || s.getClassCode().equalsIgnoreCase("PSD2") || s.getClassCode().equalsIgnoreCase("PSD3")) {
                     examClassCode = "5M0529";

                         }
                      if (s.getClassCode().equalsIgnoreCase("DG1") || s.getClassCode().equalsIgnoreCase("DG2") || s.getClassCode().equalsIgnoreCase("DG3")) {
                      examClassCode = "5M2768";

                         }
                       if (s.getClassCode().equalsIgnoreCase("ECS1") || s.getClassCode().equalsIgnoreCase("ECS2") || s.getClassCode().equalsIgnoreCase("ECS3")) {
                           examClassCode = "5M4468";

                           }
                      if (s.getClassCode().equalsIgnoreCase("ASD1") || s.getClassCode().equalsIgnoreCase("ASD2") || s.getClassCode().equalsIgnoreCase("ASD3")) {
                           examClassCode = "6M0691";

                          }
                       if (s.getClassCode().equalsIgnoreCase("AAS1") || s.getClassCode().equalsIgnoreCase("AAS2") || s.getClassCode().equalsIgnoreCase("AAS3")) {
                          examClassCode = "6M5153";

                          }
                       
                        if (examClassCode.equals(courseCode)){ 
                          jTextFieldA1.setEnabled(true);
                          jTextFieldA2.setEnabled(true);
                          jTextFieldExam.setEnabled(true);
                       // clear table
                            for (int ii = 0; ii < 24; ii++) {
                            
                            jTableStudent.setValueAt("", ii, 0);
                            jTableStudent.setValueAt("" ,ii, 1);
                            jTableStudent.setValueAt("", ii, 2);
                            jTableStudent.setValueAt("", ii, 3);
                            jTableStudent.setValueAt("", ii, 4);
                            jTableStudent.setValueAt("", ii, 5);
                            jTableStudent.setValueAt("", ii, 6);
                            jTableStudent.setValueAt("", ii, 7);
                                      }

            String SQL = "SELECT studentID, firstName, surname FROM student WHERE classGroupCode = ?";

            PreparedStatement prest = con.prepareStatement(SQL);

            prest.setString(1, s.getClassCode());
            

            ResultSet rs = prest.executeQuery();

            while (rs.next()) {
                System.out.println(1);
                s.setStudentID(rs.getInt(1));
                s.setFirstName(rs.getString(2));
                s.setSurname(rs.getString(3));
                
                   
                    
                     //get student grades
                          String SQLM = "SELECT assesmnet.assignment1, assesmnet.assignment2, assesmnet.exam, assesmnet.result, assesmnet.moduleCode, assesmnet.assignmentID FROM assesmnet INNER JOIN student_has_assesmnet ON assesmnet.assignmentID = student_has_assesmnet.assignmentID WHERE assesmnet.moduleCode = ? AND student_has_assesmnet.studentID = ? ";

                          PreparedStatement prestM = con.prepareStatement(SQLM);
                
               
                          prestM.setString(1, moduleCode);
                          prestM.setInt(2, s.getStudentID());
                          

                         ResultSet rsM = prestM.executeQuery();
                         
                          s.setAssignment1(0);
                          s.setAssignment2(0);
                          s.setExam(0);
                          s.setTotal(0);
                          assignmentID = (0);
                          result = "N/A";

                        while (rsM.next()) {
                          s.setAssignment1(rsM.getInt(1));
                          s.setAssignment2(rsM.getInt(2));
                          s.setExam(rsM.getInt(3));
                          s.setTotal(rsM.getInt(4));
                          assignmentID = (rsM.getInt(6));
                           int total = s.getTotal();
                            result = "";
                    if (total > 79){
                        result = "Distinction!";
                    } else if (total > 64){
                        result = "Merit!";
                    } else if (total > 49){
                        result = "Pass";
                    } else if (total > 0){
                        result = "unsucessful";
                    } else {
                        result = "N/A";
                    }
                    
                     
                } 
            
                        counter++;
                        //populate table
                        for (int i = 0; i < 1; i++) {
                            
                            jTableStudent.setValueAt(assignmentID, counter, 0);
                            jTableStudent.setValueAt(moduleCode ,counter, 1);
                            jTableStudent.setValueAt(s.getAssignment1(), counter, 2);
                            jTableStudent.setValueAt(s.getAssignment2(), counter, 3);
                            jTableStudent.setValueAt(s.getExam(), counter, 4);
                            jTableStudent.setValueAt(result, counter, 5);
                            jTableStudent.setValueAt(s.getFirstName(), counter, 6);
                            jTableStudent.setValueAt(s.getSurname(), counter, 7);
                          
                        }
            } 
            
            counter = -1;
            prest.close();
            con.close();
            
               } else {
                   JOptionPane.showMessageDialog(null, "This is not your class group therefore you cannot edit their results!");
               }
                
            
        } catch (SQLException err) {

            System.out.println(err.getMessage());

        }
            } else {
               JOptionPane.showMessageDialog(null, "Please enter a valid Class Group!"); 
            }
        }else {
            JOptionPane.showMessageDialog(null, "Please enter Class Group first!");
        }
    }//GEN-LAST:event_jButtonConfirmJTableActionPerformed

    private void jButtonAddJTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddJTableActionPerformed
        if (!(jTextFieldSearch1.getText().equals(""))){
            int[] index = jTableStudent.getSelectedRows();
            if (!(index.length == 0)){
           
        try {

            Connection conn = DriverManager.getConnection(url + dbName, userName, password);

            System.out.print("testing connection to database");
            
            Student s = new Student();
            
             
             
                     for (int i = 0; i < index.length; i++) {
               s.setSurname(jTableStudent.getValueAt(index[i], 7).toString());
           
                 }
        //get student id
        String SQL1 = "SELECT studentID FROM student WHERE surname = ?";

        PreparedStatement prest1 = conn.prepareStatement(SQL1);

        prest1.setString(1, s.getSurname());
            

            ResultSet rs1 = prest1.executeQuery();

            while (rs1.next()) {
                s.setStudentID(rs1.getInt(1));
            }
            //get student grades
             String SQLM = "SELECT assesmnet.assignment1, assesmnet.assignment2, assesmnet.exam, assesmnet.result, assesmnet.moduleCode FROM assesmnet INNER JOIN student_has_assesmnet ON assesmnet.assignmentID = student_has_assesmnet.assignmentID WHERE assesmnet.moduleCode = ? AND student_has_assesmnet.studentID = ?  ";

                PreparedStatement prestM = conn.prepareStatement(SQLM);
                
                prestM.setString(1, moduleCode);
                prestM.setInt(2, s.getStudentID());

                ResultSet rsM = prestM.executeQuery();

                if (!(rsM.next())) {

            PreparedStatement prest2;
            
             int A1 ;
             int A2 ;
                String A1S = jTextFieldA1.getText();
                String A2S = jTextFieldA2.getText();
                String examS = jTextFieldExam.getText();
                int exam ;
                String result = "";
                int total = 0;
        
       
        if (A1S.length() == 0) {
            
            jTextFieldA1.setText("Assesment 1 Not Completed");
            A1 = 0;
  
        } else{
            A1 = Integer.parseInt(jTextFieldA1.getText());
        
        }   if (A2S.length() == 0) {
            
            jTextFieldA2.setText("Assesment 2 not completed");
             A2 = 0;

        } else{
            A2 = Integer.parseInt(jTextFieldA2.getText());
            
        }   if (examS.length() == 0) {
            
            jTextFieldExam.setText("Exam not completed");
             exam = 0;

        } else {
            exam = Integer.parseInt(jTextFieldExam.getText());
        }

            
            total = (A1 + A2 + exam) ;
             s.setAssignment1(A1);
             s.setAssignment2(A2);
             s.setExam(exam);
             s.setTotal(total);
                
            s.setClassCode(jTextFieldSearch1.getText());
            
                  
                
                if (total > 79){
                    result = "Distinction!";
                } else if (total > 64){
                    result = "Merit!";
                } else if (total > 49){
                    result = "Pass";
                } else if (total > 0){
                    result = "unsucessful";
                } else {
                    result = "N/A";
                }
                //get max assignment id and add 1
                String SQLMax = "SELECT MAX(assignmentID) FROM gtirecords.assesmnet";
                PreparedStatement prestMax = conn.prepareStatement(SQLMax);
                 ResultSet rs = prestMax.executeQuery();
                while (rs.next()) {
                    assignmentID =((rs.getInt(1) + 1));
                    
                }
                
           
               
        System.out.println(1);
        
        //insert student grades into database
        String sql2 = "INSERT INTO assesmnet (assignmentID, moduleCode, assignment1, assignment2, exam, result) VALUES (?,?,?,?,?,?)";

            prest2 = conn.prepareStatement(sql2);
            

            prest2.setInt(1, assignmentID);
            prest2.setString(2, moduleCode);
            prest2.setInt(3, s.getAssignment1());
            prest2.setInt(4, s.getAssignment2());
            prest2.setInt(5, s.getExam());
            prest2.setInt(6, s.getTotal());
            
            String SQLA = "INSERT INTO student_has_assesmnet (studentID, assignmentID) VALUES (?,?)";
                PreparedStatement prestA = conn.prepareStatement(SQLA);
                prestA.setInt(1, s.getStudentID());
                 prestA.setInt(2, assignmentID);
                 
            
            int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to Add Results?");

            if (confirm == 0) {

                prest2.executeUpdate();
                prestA.executeUpdate();
                jTextFieldResult.setText(result);
                jButtonConfirmJTable.doClick();
                JOptionPane.showMessageDialog(this, "Results have been added succesfully!");

 
            } else {

                JOptionPane.showMessageDialog(this, "No problem!");

            }

            prest2.close();
            prestA.close();
            conn.close();
            
            
            
                } else{
                     JOptionPane.showMessageDialog(null, "Results have already been added!");
                }
            
        } catch (SQLException err) {

            System.out.println(err.getMessage());

            JOptionPane.showMessageDialog(null, "Not found!");

        }
           
            }else {
            JOptionPane.showMessageDialog(null, "Please highlight a student first!");
        }
            
        } else {
            JOptionPane.showMessageDialog(null, "Please search for class group first!");
        }
    }//GEN-LAST:event_jButtonAddJTableActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teacherGradesFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teacherGradesFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teacherGradesFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teacherGradesFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teacherGradesFrame2().setVisible(true);
            }
        });
    }
    
    

    public static boolean isSlash(char c) {

        boolean hasDot = false;

        if (c == '/') {

            hasDot = true;

        } else {

            hasDot = false;

        }

        return hasDot;

    }
//clear textfields
    public void clear() {
        jTextFieldStudentID.setText("");
        jTextFieldA1.setText("");
        jTextFieldA2.setText("");
        jTextFieldExam.setText("");
        jTextFieldResult.setText("");
    }
    
  
       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonAddJTable;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonConfirm;
    private javax.swing.JButton jButtonConfirmJTable;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonStudent;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableStudent;
    private javax.swing.JTextField jTextFieldA1;
    private javax.swing.JTextField jTextFieldA2;
    private javax.swing.JTextField jTextFieldExam;
    private javax.swing.JTextField jTextFieldResult;
    private javax.swing.JTextField jTextFieldSearch;
    private javax.swing.JTextField jTextFieldSearch1;
    private javax.swing.JTextField jTextFieldStudentID;
    // End of variables declaration//GEN-END:variables
}
